config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  namespace :journal do
    resources :payment_store_credits do
      collection do
        put :use_store_credit_for_order
        put :use_store_credit_for_invoice
        put :use_store_credit_for_journal_invoice
      end
    end
    resources :store_credit_categories
    resources :purchase_invoices do
      member do
        get :add_items
        put :update_cart
        put :confirm
        get :paid
        get :refund
        put :refund_cart
        get :add_note
        put :update_note
        get :print
        get :reverse_to_draft
      end
    end
    resources :categories
    resources :accounts
    resources :reports do
      collection do
        get :trial_balance
        get :general_ledger
        get :balance_sheet
        get :transaction
        get :cash_and_bank
        get :profit_and_loss
        get :cash_flow_statement
      end
    end
    resources :transaction_rmbs
    resources :transactions do
      member do
        get :record_payment
        put :record_container
        put :record_order
        put :record_invoice
        put :record_purchase
        put :record_bill
        put :record_journal_invoice
        get :transfer
        put :transfer_fund
        put :add_store_credit
        get :history
        put :record_expense
        put :record_expense_transfer_fund
        put :record_income_transfer_fund
        get :add_counter_part
        put :counter_part
      end
      collection do
        put :use_store_credit_for_order
        put :use_store_credit_for_invoice
        get :show_import
        put :import
        get :all_payment_confirmed
      end
    end
    resources :transfer_funds
    resources :journal_items do
      collection do
        get :all_journal_entries
      end
    end
    resources :bills do
      member do 
        put :record_bill_rmb
        get :new_payment
        put :create_payment
      end
    end
    resources :invoices do
      member do
        get :record_invoice
        put :record_order_invoice
        put :record_invoice_cn
        get :reminder_email
        put :unpay
      end
    end
    resources :info_payments do 
      member do
        get :confirmed 
      end
    end
    resources :store_credits do
      collection do
        get :cash_out_new
        put :create_cash_out
        get :cash_out_request
        get :bill_paid
      end
    end
  end

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
    namespace :admin do
      get 'stock_items/card_stock', to: "stock_items#card_stock"
      get 'stock_items/:id/stock_movement', to: "stock_items#stock_movement", as: :stock_item_movement
      get 'stock_items/:id/stock_warehouse_movement', to: "stock_items#stock_warehouse_movement",  as: :stock_warehouse_movement
      get 'products/:id/view_buyer', to: "products#view_buyer", as: :view_buyer
      get 'products/:id/hide_show_product', to: "products#hide_show_product", as: :hide_show_product
      put 'orders/:id/payment_confirmation', to: "orders#payment_confirmation", as: :order_payment_confirmation
      get 'orders/:id/payment_confirmation_new', to: "orders#payment_confirmation_new", as: :order_payment_confirmation_new
      get 'orders/:id/lock_unlock', to: "orders#lock_unlock", as: :order_lock_unlock
      get 'orders/return_request', to: "orders#return_request", as: :customer_return_request
      get 'orders/show_inventory_unit', to: "orders#show_inventory_unit", as: :order_inventory_units
      put 'orders/:id/inventory_unit', to: "orders#backordered_inventory", as: :backordered_inventory_unit
      get 'orders/download_pending_po', to: "orders#download_pending_po", as: :download_pending_po
      get 'shipping_methods/:id/download_rates', to: "shipping_methods#download_rates", as: :download_rates
      resources :cash_out_requests do
        collection do
          get :cash_out_new
          put :create_cash_out
        end
      end
      resources :reports do
        collection do
          get :sales_ready_stock
          get :income_dp_preorder
          get :unpaid_invoice
          get :invoice_sales
          get :return_order
          get :store_credit
          get :lost_item
          get :dp_hangus
          get :cek_stock
          get :credit_note
        end
      end
      resources :return_to_suppliers do
        member do
          get :items
          put :return
          put :update_return
          put :confirm
          put :credit_to_supplier
          put :treat_as_expense
          put :ship
          put :create_invoice
        end
        collection do
          get :delete_item
        end
      end

      resources :inventory_adjustments do
        member do
          put :update_items
          put :add_item
          get :validate
        end
        collection do
          get :item_destroy
        end
      end

      resources :inventory_adjustment_categories
      # get 'reports/sales_ready_stock', to: "reports#sales_ready_stock"
      resources :price_levels
      resources :purchase_orders do
        member do
          get :items
          put :update_items
          get :payment
          get :shipment
          put :confirm
          put :add_item
          get :cart
          get :print
          get :reverse_to_pending
          get :update_after_change_item
        end
        collection do
          get :po_pending
          get :line_item_destroy
          get :all
          get :mark_completed
        end
      end
      resources :containers do
        member do
          get :new_item
          put :update_items
          put :receive_items
        end
        collection do
          get :selisih_barang
        end
      end
      resources :container_items do
        member do
          get :ready
          put :complete
          put :refund
          put :generate_po
          get :reverse
          get :delete_item
          put :treat_as_expense
        end
      end
      resources :invoices do
        member do
          get :items
          put :select_items
          get :confirm
          put :send_invoice
          get :completed
          put :dp_angus
          put :add_note
          put :flag_dropship
          get :reminder_email
          get :lock_unlock
          get :payment_confirmation_new
          put :payment_confirmation
        end
        collection do
          get :generate_invoice
        end
      end
      resources :invoice_items do
        member do
          patch :change_address
          put :add_adjustment
        end
      end

      resources :shipment_groups do
        member do
          put :update_inventory_unit
          get :ready
          get :print
          get :processing
          put :packed
          put :ship
        end
        collection do
          get :generate_shipment_group
        end
      end
      resources :news
      resources :testimonials do
        member do
          get :publish
        end
      end
      put 'new_address', to: "invoices#new_address"
    resources :shipments do
      member do
        put :ship
        put :mark_as_shipped
      end
    end
    end
    resources :testimonials
    resources :payment_confirmations
    resources :shipping_rates do
      collection do
        put :check_shipping_rate
        get :show_shipping_rate
      end
    end
    resources :cash_out_requests
    resources :return_authorization_users do 
      member do
        get :new_rma
      end
      collection do
        get :shipped_order
      end
    end
    get 'products/new_items', to: "products#new_items"
    get 'products/ready_stock', to: "products#ready_stock"
    get 'products/album', to: "products#album"
    get 'products/sale', to: "products#sale"
    put 'home/new_address', to: "home#new_address"
    get 'home/addresses', to: "home#addresses", as: :user_addresses
    get 'store_credits/:id', to: "home#store_credit"
    get 'invoice/:id', to: "home#invoice", as: :user_invoice
    get 'order/show/:id', to: "home#show_order", as: :user_order_show
    get 'invoice/:id/print', to: "home#print", as: :user_invoice_print
    get 'orders/:id/print', to: "orders#print", as: :orders_print
    get 'products/album/:id/show_album_image', to: "products#show_album_image", as: :show_album_product_image

    # buat bayar invoice pake store credit di my account
    get 'invoice/pay_with_sc/:id', to: "home#use_sc_for_invoice_po", as: :pay_sc_inv_po
    put 'invoice/pay_with_sc/:id', to: "home#pay_with_sc_invoice", as: :use_sc_inv_po

    # buat bayar order pake store credit di my account
    get 'order/pay_with_sc/:id', to: "home#use_sc_for_order", as: :pay_sc_order
    put 'order/pay_with_sc/:id', to: "home#pay_with_sc_order", as: :use_sc_order

    # buat bayar invoice_journal(credit) pake store credit di my account
    get 'credit/pay_with_sc/:id', to: "home#use_sc_for_credit", as: :pay_sc_credit
    put 'credit/pay_with_sc/:id', to: "home#pay_with_sc_credit", as: :use_sc_credit

    #ubah ekspedisi di invoice
    put 'invoice/ubah_ekspedisi/:id', to: "home#ubah_ekspedisi", as: :ubah_ekspedisi_user

  end
end

app/models/spree/payment_method/invoice.rb
module Spree
  class PaymentMethod::Invoice < PaymentMethod
    def actions
      %w{capture void}
    end

    # Indicates whether its possible to capture the payment
    def can_capture?(payment)
      ['checkout', 'pending'].include?(payment.state)
    end

    # Indicates whether its possible to void the payment.
    def can_void?(payment)
      payment.state != 'void'
    end

    def capture(*args)
      simulated_successful_billing_response
    end

    def void(*args)
      simulated_successful_billing_response
    end

    def source_required?
      false
    end

    def cancel(response)
      simulated_successful_billing_response
    end

    def credit(*args)
      simulated_successful_billing_response
    end

    private

    def simulated_successful_billing_response
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end
  end

end

app/controllers/journal/invoices_controller.rb
class Journal::InvoicesController < Journal::BaseController
  before_action :set_journal_invoice, only: [:show, :edit, :update, :destroy, :record_invoice]
  
  def index
    @q = Journal::Invoice.ransack((params[:q]))
    @invoices = @q.result.includes(:items).order(created_at: :desc).page(params[:page])
  end

  def new
    @journal_invoice = Journal::Invoice.new
    render layout:false
  end

  def show

  end

  def edit
    @journal_invoice = Journal::Invoice.find(params[:id])
    render layout: false
  end

  def update
     @journal_invoice = Journal::Invoice.find(params[:id])
 
    if @journal_invoice.update(journal_invoice_params)
      flash[:success] = "Invoices was successfully updated."
      redirect_to journal_invoices_path
    else
      flash[:danger] = "Update invoice failed."
      redirect_to journal_invoices_path
    end
  end

  def unpay
    @journal_invoice = Journal::Invoice.find(params[:id])
    if @journal_invoice.unpay!
      flash[:success] = "Invoice berhasil ditandai tidak terbayar"
      redirect_to journal_invoices_path
    else
      flash[:danger] = "Operasi gagal. Harap ulangi kembali."
      redirect_to journal_invoices_path
    end
  end

  def create
    param = params[:journal_invoice]
    user = Spree::User.find_by_id params[:journal_invoice][:spree_user_id]
    journal_account = Journal::Account.find_by_id param[:category]
    invoice = Journal::Invoice.create(vendor: user.name, currency: journal_account.currency, due_date: param[:due_date], total: param[:total], payment_state: "pending", spree_user_id: user.id, originator_type: "Invoice::Order")
    invoice.items.create(category: param[:category], amount: param[:total], description: param[:description], invoice_id: invoice.id)
    redirect_to journal_invoices_path, notice: "Invoices Created."
  end

  def destroy
    @journal_invoice = Journal::Invoice.find(params[:id])
    if @journal_invoice.destroy
      flash[:success] = "Invoice was successfully deleted."
      redirect_to journal_invoices_path
    else
      flash[:danger] = "Delete Invoice failed."
      redirect_to journal_invoices_path
    end
  end

  def record_invoice
    @order_payments_invoice = Spree::Order.payment_state_is("balance_due").filter(params.slice(:name_user, :number)).page(params[:page]).per(30)
    @invoice_payments = Spree::Invoice.valid.where(:status => "pending_payment").filter(params.slice(:name_user)).page(params[:page]).per(30) 
  end

  def record_order_invoice
    if set_journal_invoice.total < total_order_amount
      redirect_to request.referrer, alert: "Amount Kurang"
    else
      params[:r].each do |order_id|
        order = Spree::Order.find_by_id order_id
        payment = order.payments.create({ :amount => order.outstanding_balance, :payment_method => Spree::PaymentMethod::BankTransfer.first, :is_cn => true})
        payment.started_processing!
        payment.pend!
        payment.complete!
        order.update!
      end
      redirect_to request.referrer, notice: "Invoice Order successfully recorded"
    end
  end

  def record_invoice_cn
    if set_journal_invoice.total < total_invoice_amount
      redirect_to request.referrer, alert: "Amount Kurang"
    else
      params[:r].each do |invoice_id|
        invoice = Spree::Invoice.find_by_id invoice_id
        payment_amount = invoice.outstanding_balance
        invoice_payment = Spree::InvoicePayment.create(:invoice_id => invoice.id, :amount => payment_amount, 
          :payment_method_id => Spree::PaymentMethod::BankTransfer.first.id, :state => "checkout", user_id: whodunnit.id)
        invoice_payment.update_attributes(state: "paid", journal_transaction_id: params[:id], is_cn: true)
        invoice.update!
        invoice.send_email_payment_confirmation(params[:id])
      end
      redirect_to request.referrer, notice: "Invoice successfully recorded from CN"
    end
  end

  def reminder_email
    @invoice = Journal::Invoice.find_by_id params[:id]
    if @invoice.send_email_invoice
      @invoice.send_sms_invoice
      flash[:success] = "Email & SMS sent"
    else
      flash[:error] = "Something went wrong! Please try again"
    end
    redirect_to request.referrer
  end

  private

  def set_journal_invoice
    @journal_invoice = Journal::Invoice.find(params[:id])
  end 

  def journal_invoice_params
    params.require(:journal_invoice).permit(:vendor, :currency, :due_date, :total, :payment_state, :spree_user_id, :category, :amount, :description, :originator_type)
  end

  def whodunnit
    current_spree_user
  end

  def total_order_amount
    total_order_amount = 0
    params[:r].each do |order_id|
      total_order_amount += Spree::Order.find_by_id(order_id).outstanding_balance
    end
    return total_order_amount.to_i
  end

  def total_invoice_amount
    total_invoice_amount = 0
    params[:r].each do |invoice_id|
      total_invoice_amount += Spree::Invoice.find_by_id(invoice_id).outstanding_balance
    end
    return total_invoice_amount.to_i
  end
end

app/helpers/spree/admin/invoices_helper.rb
module Spree::Admin::InvoicesHelper
  def total_amount(items, shipment)
    items.sum(:total_amount) + shipment.try(:cost).to_i
  end
end

app/views/spree/admin/invoices/confirm.haml
%fieldset{"data-hook" => "new_product"}
  %legend{:align => "center"} Shipment
  - @shipping_addresses.each do |address|
    %table
      %thead
        %tr
          %th Order ID
          %th Image
          %th Name
          %th Pack Qty
          %th Items per Pack
          %th Total Items
          %th Price
          %th Discount
          %th Total Price
          %th Shipping Address
      %tbody
        - @invoice_items.where(ship_address_id: address).each do |invoice_item|
          %tr
            %td.align-center= invoice_item.inventory_unit.order.number
            %td.align-center= image_tag invoice_item.inventory_unit.variant.display_image.attachment(:mini)
            %td.align-center= invoice_item.inventory_unit.variant.sku
            %td.align-center= invoice_item.quantity
            %td.align-center= invoice_item.inventory_unit.line_item.qty_per_pack
            %td.align-center= invoice_item.total_pieces
            %td.align-center= invoice_item.inventory_unit.line_item.single_money.to_html
            %td.align-center
              = form_for invoice_item, url: add_adjustment_admin_invoice_item_path(invoice_item), method: :put do |f|
                = f.text_field :adjustment_total, style: "width:50%"
                = f.submit "save"
            %td.align-center= number_to_currency invoice_item.total_amount
            %td.align-center
              = form_for invoice_item, url: change_address_admin_invoice_item_url(invoice_item), html: {style: "display: inline;"} do |f|
                = f.select :ship_address_id, options_from_collection_for_select(@user_address, :address_id, ->(user_address){user_address.address.address1}, address), {}, {class: "select2", style: "width:90%", :onchange => 'this.form.submit()'}
              = link_to "", "", class: 'fa fa-plus form-address', "data-toggle" => "modal", "data-target" => "#myModal", "data-invoice-item-id" => "#{invoice_item.id}"
  .align-center
    = form_for "shipment", :url => send_invoice_admin_invoice_path(@invoice), method: :put do |f|
      = f.select :courier, Spree::ShippingMethod.all.map {|s| [s.name, s.id]}, {:include_blank => false}, :class => 'select2'
      = f.submit "Send Invoice"
    =# link_to "Send Invoice !", send_invoice_admin_invoice_path(@invoice), class: 'btn btn-default'
  %hr
    = form_for "dropship", :url => flag_dropship_admin_invoice_path(@invoice), method: :put do |f|
      .row
        .col-sm-3
          .label-input
            .label-wrap
              = label_tag :dropship
            .input-wrap
              = f.check_box :dropship
        .hidden-dropship
          .col-sm-3
            .label-input
              .label-wrap
                = label_tag :dropship_name, "Nama Pengirim"
              .input-wrap
                = f.text_field :dropship_name
          .col-sm-3
            .label-input
              .label-wrap
                = label_tag :dropship_phone, "No. Telepon Pengirim"
              .input-wrap
                = f.text_field :dropship_phone
          .col-sm-3
            = f.submit "Save Dropship"
.bootstrap-3
  #myModal.modal.fade{:role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        = form_for Spree::Address.new, url: admin_new_address_path, method: :put do |f|
          .modal-header
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"} ×
            %h4.modal-title New Address
          .modal-body
            .form-group
              = f.label :firstname
              = f.text_field :firstname, class: 'form-control', required: true
            .form-group
              = f.label :lastname
              = f.text_field :lastname, class: 'form-control', required: true
            .form-group
              = f.label :address1
              = f.text_field :address1, class: 'form-control', required: true
            .form-group
              = f.label :address2
              = f.text_field :address2, class: 'form-control', required: true
            .form-group
              = f.label :phone
              = f.text_field :phone, class: 'form-control', required: true
            .form-group
              = f.label :country_id
              = f.collection_select :country_id, available_countries, :id, :name, {}, {:class => 'required form-control select-country', required: true}
            .form-group
              = f.label :state_id
              = f.grouped_collection_select :state_id, Spree::Country.order(:name), :states, :name, :id, :name, {include_blank: true}, {class: "select-state form-control", required: true}
            .form-group
              = f.label :city
              = f.grouped_collection_select :city, Spree::State.order(:name), :cities, :name, :name, :name, {include_blank: true}, {class: "select-city form-control", required: true}
            .form-group
              = f.label :zipcode
              = f.text_field :zipcode, class: 'form-control', required: true
            = hidden_field_tag :invoice_id, {} ,{class: 'invoice-item-id'}
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
            = f.submit "Create Address", {style: "color: white;"}


:javascript
  $(document).ready(function(){
    $('.form-address').on('click', function(){
      var invoice_item_id = $(this).data('invoice-item-id');
      console.log(invoice_item_id);
      $('input.invoice-item-id').val(invoice_item_id);
    });
  });
  if ($("#dropship_dropship").is(":checked")){
    $(".hidden-dropship").show();
  } else {
    $(".hidden-dropship").hide();
  };
  $("#dropship_dropship").on("change", function(){
    if ($("#dropship_dropship").is(":checked")){
      $(".hidden-dropship").show();
    } else {
      $(".hidden-dropship").hide();
    };
  });

app/views/spree/admin/invoices/index.haml
- admin_breadcrumb(plural_resource_name(Spree::Invoice))

- content_for :page_actions do
  %li
    = button_link_to "New Invoice", new_admin_invoice_url()
  %li
    = button_link_to "Generate Invoice", generate_invoice_admin_invoices_path
= form_for('Filter_invoice', :as => 'filter_invoice', method: :get, :url => admin_invoices_path) do |f|
  .row
    .col-sm-3
      .form-group.form-group-default.required
        %label Payment Status
        %br
        = select_tag 'payment_is', options_for_select([["Paid", "paid"], ["Waiting Confirmation", "waiting_confirmation"], ["Pending", "pending_payment"], ["Cancel", "canceled"]]), {class: "form-control", :class => 'select2', prompt: "Select Payment Status"}
    .col-sm-3
      .form-group.form-group-default.required
        %label Customer Name
        = text_field_tag 'name_contain', nil, class: 'form-control'
    .col-sm-3
      .form-group.form-group-default.required
        %label Invoice ID
        = text_field_tag 'id_is', nil, class: 'form-control'
    .col-sm-3
      .form-group.form-group-default.required
        %label Status Lock/Unlock
        %br
        = select_tag 'lock_is', options_for_select([["Lock", 1], ["Unlock", 0]]), {class: "form-control", :class => 'select2', prompt: "Select"}
  .row
    .col-sm-12.align-center
      %br
      = f.submit "Search", class: "btn btn-success"
-if @invoices.any? 
  = paginate @invoices, theme: "solidus_admin" 
  %table
    %thead
      %tr
        %th.align-left{style: "width: 10%"} Created at
        %th.align-left{style: "width: 5%"} ID
        %th.align-left{style: "width: 15%"} Name
        %th.align-left{style: "width: 15%"} Status
        %th.align-left{style: "width: 15%"} Total
        %th.align-left{style: "width: 10%"} Payment total
        %th.align-left{style: "width: 10%"} Notes
        %th.align-left{style: "width: 10%"} Created By
    %tbody
      - @invoices.each do |c|
        %tr
          %td= c.created_at.to_date
          %td= link_to c.id, admin_invoice_path(c.id), class: 'the-invoice-id'
          %td= c.user.name
          %td
            - if c.status == "pending_payment"
              - if c.payment_confirmations.empty?
                = c.status.humanize
              - else
                Waiting for Confirmation
            - else
              = c.status.humanize
          -if !c.total.nil? 
            %td= number_to_idr c.total-c.dp_paid
          -else
            %td belum selesai
          %td
            - if c.status == "pending_payment"
              = number_to_idr c.payments.paid.sum(:amount)
          %td= c.note.truncate(25) if !c.note.nil?
          %td= Spree::User.find_by_id(c.created_by_id).nil? ? "System" : Spree::User.find_by_id(c.created_by_id).name
          %td.actions
            - if c.lock?
              = link_to "", lock_unlock_admin_invoice_path(c), class: 'fa fa-lock icon_link with-tip no-text', "data-original-title" => "Unlock Invoice!", data: {confirm: "Apakah anda yakin akan membuka order ini? jika order terbuka akan tampil ketika generate shipment"}
            - else
              = link_to "", lock_unlock_admin_invoice_path(c), class: 'fa fa-unlock icon_link with-tip no-text', "data-original-title" => "Lock Invoice!", data: {confirm: "Apakah anda yakin akan mengunci order ini? jika order terkunci tidak akan keluar ketika generate shipment"}
            - if c.pending_payment?
              - if c.payment_confirmations.blank?
                = link_to "", payment_confirmation_new_admin_invoice_path(c), class: 'fa fa-check-square icon_link with-tip no-text', "data-original-title" => "Payment Confirmation"
              = link_to_with_icon 'close', "DP Hangus", dp_angus_admin_invoice_path(c), :no_text => true, method: :put
              = link_to_with_icon 'envelope', "Reminder Email", reminder_email_admin_invoice_path(c), :no_text => true
              - if c.payments.paid.sum(:amount) > 0
                = link_to_with_icon 'trash', "Hapus",  admin_invoice_path(c), :method=>:delete, :class=>:destroy, :data => { :confirm => 'Sebagian pembayaran telah dilakukan pada invoice ini. Apakah anda yakin akan tetap menghapus invoice ini?'}, :no_text => true
              - else
                = link_to_delete c, :no_text => true if can?(:delete, c)
              = link_to_with_icon 'pencil-square-o', "Edit", confirm_admin_invoice_path(c), :no_text => true, method: :get
            %i.fa.fa-sticky-note.note-button{"data-toggle" => "modal", "data-target" => "#add-note"}
  = paginate @invoices, theme: "solidus_admin" 
- else
  .alpha.twelve.columns.no-objects-found
    = render 'spree/admin/shared/no_objects_found', resource: Spree::Invoice, new_resource_url: new_object_url
#add-note.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title Add Notes
      .modal-body
        .panel-body
          -if !@invoices.first.nil?
            = form_for "update_note", :url => add_note_admin_invoice_path(@invoices.first), method: :put, html: {class: 'the-form-modal'} do |f|
              .form-group.form-group-default.required
                = f.label "Add Note"
                = f.text_area :note, class: "input form-control"
              .actions
                = f.submit 'Submit', class: "btn btn-success"

:javascript
  $('.note-button').on('click', function(event){
    var route = $(this).closest('tr').find('.the-invoice-id').attr('href') + '/add_note';
    console.log(route);

    $('.the-form-modal').attr('action', route);
  });

app/views/spree/admin/invoices/items.haml
%fieldset{"data-hook" => "new_product"}
  %legend{:align => "center"} Select Items
  = form_tag select_items_admin_invoice_path, method: :put do 
    %table
      %thead
        %tr
          %th= check_box_tag "select-all"
          %th Order ID
          %th Image
          %th Name
          %th Pack Qty
          %th Items per Pack
          %th Total Items
          %th Price
          %th Total Price
          %th Courier Chosen
      %tbody.activate-toggle-checkbox-button
        - @order_items.each do |inventory_unit|
          - quantity = inventory_unit.expected_shipped > 0 ? inventory_unit.expected_shipped_in_pack : inventory_unit.line_item.quantity
          - total_items = quantity * inventory_unit.line_item.qty_per_pack
          - total_amount_per_item = inventory_unit.line_item.price * total_items
          %tr
            %td.align-center= check_box_tag "select_items[]", inventory_unit.id
            %td.align-center= inventory_unit.order.number
            %td.align-center= image_tag inventory_unit.variant.display_image.attachment(:mini)
            %td.align-center= inventory_unit.variant.sku
            %td.align-center= text_field_tag "select_items_2[#{inventory_unit.id}]", quantity
            %td.align-center= inventory_unit.line_item.qty_per_pack
            %td.align-center= total_items
            %td.align-center= inventory_unit.line_item.single_money.to_html
            %td.align-center= number_to_idr total_amount_per_item
            %td.align-center= inventory_unit.order.shipments.first.shipping_method.name
    = submit_tag "Next"

:javascript
  $( '#select-all' ).click( function () {
    $( '.activate-toggle-checkbox-button input[type="checkbox"]' ).prop('checked', this.checked)
  })

app/views/spree/admin/invoices/new.haml
= render :partial => 'spree/shared/error_messages', :locals => { :target => @invoice }
= form_for [:admin, @invoice], method: :post, url: admin_invoices_path, :html => { :multipart => true } do |f|
  %fieldset{"data-hook" => "new_product"}
    %legend{:align => "center"} New Invoice
    .sixteen.columns.alpha
      = f.field_container :user do
        = f.label :user, "Nama", class: 'required'
        %br/
        = f.collection_select(:user_id, @customers, :user_id, ->(order){order.user.name}, { :include_blank => Spree.t('match_choices.none') }, { :class => 'select2', style: "width: 100%" })
        = f.error_message_on :user
    .clearfix
    = render :partial => 'spree/admin/shared/new_resource_links'