config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  namespace :journal do
    resources :payment_store_credits do
      collection do
        put :use_store_credit_for_order
        put :use_store_credit_for_invoice
        put :use_store_credit_for_journal_invoice
      end
    end
    resources :store_credit_categories
    resources :purchase_invoices do
      member do
        get :add_items
        put :update_cart
        put :confirm
        get :paid
        get :refund
        put :refund_cart
        get :add_note
        put :update_note
        get :print
        get :reverse_to_draft
      end
    end
    resources :categories
    resources :accounts
    resources :reports do
      collection do
        get :trial_balance
        get :general_ledger
        get :balance_sheet
        get :transaction
        get :cash_and_bank
        get :profit_and_loss
        get :cash_flow_statement
      end
    end
    resources :transaction_rmbs
    resources :transactions do
      member do
        get :record_payment
        put :record_container
        put :record_order
        put :record_invoice
        put :record_purchase
        put :record_bill
        put :record_journal_invoice
        get :transfer
        put :transfer_fund
        put :add_store_credit
        get :history
        put :record_expense
        put :record_expense_transfer_fund
        put :record_income_transfer_fund
        get :add_counter_part
        put :counter_part
      end
      collection do
        put :use_store_credit_for_order
        put :use_store_credit_for_invoice
        get :show_import
        put :import
        get :all_payment_confirmed
      end
    end
    resources :transfer_funds
    resources :journal_items do
      collection do
        get :all_journal_entries
      end
    end
    resources :bills do
      member do 
        put :record_bill_rmb
        get :new_payment
        put :create_payment
      end
    end
    resources :invoices do
      member do
        get :record_invoice
        put :record_order_invoice
        put :record_invoice_cn
        get :reminder_email
        put :unpay
      end
    end
    resources :info_payments do 
      member do
        get :confirmed 
      end
    end
    resources :store_credits do
      collection do
        get :cash_out_new
        put :create_cash_out
        get :cash_out_request
        get :bill_paid
      end
    end
  end

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
    namespace :admin do
      get 'stock_items/card_stock', to: "stock_items#card_stock"
      get 'stock_items/:id/stock_movement', to: "stock_items#stock_movement", as: :stock_item_movement
      get 'stock_items/:id/stock_warehouse_movement', to: "stock_items#stock_warehouse_movement",  as: :stock_warehouse_movement
      get 'products/:id/view_buyer', to: "products#view_buyer", as: :view_buyer
      get 'products/:id/hide_show_product', to: "products#hide_show_product", as: :hide_show_product
      put 'orders/:id/payment_confirmation', to: "orders#payment_confirmation", as: :order_payment_confirmation
      get 'orders/:id/payment_confirmation_new', to: "orders#payment_confirmation_new", as: :order_payment_confirmation_new
      get 'orders/:id/lock_unlock', to: "orders#lock_unlock", as: :order_lock_unlock
      get 'orders/return_request', to: "orders#return_request", as: :customer_return_request
      get 'orders/show_inventory_unit', to: "orders#show_inventory_unit", as: :order_inventory_units
      put 'orders/:id/inventory_unit', to: "orders#backordered_inventory", as: :backordered_inventory_unit
      get 'orders/download_pending_po', to: "orders#download_pending_po", as: :download_pending_po
      get 'shipping_methods/:id/download_rates', to: "shipping_methods#download_rates", as: :download_rates
      resources :cash_out_requests do
        collection do
          get :cash_out_new
          put :create_cash_out
        end
      end
      resources :reports do
        collection do
          get :sales_ready_stock
          get :income_dp_preorder
          get :unpaid_invoice
          get :invoice_sales
          get :return_order
          get :store_credit
          get :lost_item
          get :dp_hangus
          get :cek_stock
          get :credit_note
        end
      end
      resources :return_to_suppliers do
        member do
          get :items
          put :return
          put :update_return
          put :confirm
          put :credit_to_supplier
          put :treat_as_expense
          put :ship
          put :create_invoice
        end
        collection do
          get :delete_item
        end
      end

      resources :inventory_adjustments do
        member do
          put :update_items
          put :add_item
          get :validate
        end
        collection do
          get :item_destroy
        end
      end

      resources :inventory_adjustment_categories
      # get 'reports/sales_ready_stock', to: "reports#sales_ready_stock"
      resources :price_levels
      resources :purchase_orders do
        member do
          get :items
          put :update_items
          get :payment
          get :shipment
          put :confirm
          put :add_item
          get :cart
          get :print
          get :reverse_to_pending
          get :update_after_change_item
        end
        collection do
          get :po_pending
          get :line_item_destroy
          get :all
          get :mark_completed
        end
      end
      resources :containers do
        member do
          get :new_item
          put :update_items
          put :receive_items
        end
        collection do
          get :selisih_barang
        end
      end
      resources :container_items do
        member do
          get :ready
          put :complete
          put :refund
          put :generate_po
          get :reverse
          get :delete_item
          put :treat_as_expense
        end
      end
      resources :invoices do
        member do
          get :items
          put :select_items
          get :confirm
          put :send_invoice
          get :completed
          put :dp_angus
          put :add_note
          put :flag_dropship
          get :reminder_email
          get :lock_unlock
          get :payment_confirmation_new
          put :payment_confirmation
        end
        collection do
          get :generate_invoice
        end
      end
      resources :invoice_items do
        member do
          patch :change_address
          put :add_adjustment
        end
      end

      resources :shipment_groups do
        member do
          put :update_inventory_unit
          get :ready
          get :print
          get :processing
          put :packed
          put :ship
        end
        collection do
          get :generate_shipment_group
        end
      end
      resources :news
      resources :testimonials do
        member do
          get :publish
        end
      end
      put 'new_address', to: "invoices#new_address"
    resources :shipments do
      member do
        put :ship
        put :mark_as_shipped
      end
    end
    end
    resources :testimonials
    resources :payment_confirmations
    resources :shipping_rates do
      collection do
        put :check_shipping_rate
        get :show_shipping_rate
      end
    end
    resources :cash_out_requests
    resources :return_authorization_users do 
      member do
        get :new_rma
      end
      collection do
        get :shipped_order
      end
    end
    get 'products/new_items', to: "products#new_items"
    get 'products/ready_stock', to: "products#ready_stock"
    get 'products/album', to: "products#album"
    get 'products/sale', to: "products#sale"
    put 'home/new_address', to: "home#new_address"
    get 'home/addresses', to: "home#addresses", as: :user_addresses
    get 'store_credits/:id', to: "home#store_credit"
    get 'invoice/:id', to: "home#invoice", as: :user_invoice
    get 'order/show/:id', to: "home#show_order", as: :user_order_show
    get 'invoice/:id/print', to: "home#print", as: :user_invoice_print
    get 'orders/:id/print', to: "orders#print", as: :orders_print
    get 'products/album/:id/show_album_image', to: "products#show_album_image", as: :show_album_product_image

    # buat bayar invoice pake store credit di my account
    get 'invoice/pay_with_sc/:id', to: "home#use_sc_for_invoice_po", as: :pay_sc_inv_po
    put 'invoice/pay_with_sc/:id', to: "home#pay_with_sc_invoice", as: :use_sc_inv_po

    # buat bayar order pake store credit di my account
    get 'order/pay_with_sc/:id', to: "home#use_sc_for_order", as: :pay_sc_order
    put 'order/pay_with_sc/:id', to: "home#pay_with_sc_order", as: :use_sc_order

    # buat bayar invoice_journal(credit) pake store credit di my account
    get 'credit/pay_with_sc/:id', to: "home#use_sc_for_credit", as: :pay_sc_credit
    put 'credit/pay_with_sc/:id', to: "home#pay_with_sc_credit", as: :use_sc_credit

    #ubah ekspedisi di invoice
    put 'invoice/ubah_ekspedisi/:id', to: "home#ubah_ekspedisi", as: :ubah_ekspedisi_user

  end
end

app/models/spree/order/order_cancellations_decorator.rb
Spree::OrderCancellations.class_eval do
  def short_ship(inventory_units, whodunnit:nil)
    if inventory_units.map(&:order_id).uniq != [@order.id]
      raise ArgumentError, "Not all inventory units belong to this order"
    end

    unit_cancels = []

    Spree::Order.transaction do
      Spree::OrderMutex.with_lock!(@order) do
        Spree::InventoryUnit.transaction do
          inventory_units.each do |iu|
            unit_cancels << short_ship_unit(iu, whodunnit: whodunnit)
          end

          update_shipped_shipments(inventory_units)
          Spree::OrderMailer.inventory_cancellation_email(@order, inventory_units.to_a).deliver_later if Spree::OrderCancellations.send_cancellation_mailer
        end

        @order.update!

        refund_to_store_credit(inventory_units)

        @order.update!


        if short_ship_tax_notifier
          short_ship_tax_notifier.call(unit_cancels)
        end
      end
    end

    if @order.inventory_units.not_canceled.count < 1 
      @order.shipments.update_all(state: "canceled")
      @order.update_columns(state: "canceled", shipment_state: "canceled", payment_state: "void")
    end

    unit_cancels
  end

  private

  def restock(inventory_unit, unit_cancel)
    if inventory_unit.on_hand?
      inventory_unit.shipment.stock_location.restock inventory_unit.variant, inventory_unit.line_item.quantity, unit_cancel
    end

    if inventory_unit.backordered?
      inventory_unit.shipment.stock_location.restock_backordered inventory_unit.variant, inventory_unit.line_item.quantity, 
      inventory_unit.outstanding_unit, unit_cancel
    end
  end

  def short_ship_unit(inventory_unit, whodunnit:nil)
    unit_cancel = Spree::UnitCancel.create!(
      inventory_unit: inventory_unit,
      reason: Spree::UnitCancel::DEFAULT_REASON,
      created_by: whodunnit
    )
    unit_cancel.adjust!
    restock(inventory_unit, unit_cancel)
    if !inventory_unit.canceled?
      inventory_unit.cancel!
      post_journal_inventory_from_cancel_item(inventory_unit) if @order.paid? && !@order.preorder?
    end
    unit_cancel
  end

  def post_journal_inventory_from_cancel_item(inventory_unit)
    @inventory = Journal::Account.find_by_code("1-10203").id
    @cost_of_sales = Journal::Account.find_by_code("5-50401").id
    qty_cancel = inventory_unit.split_invoice? ? inventory_unit.expected_shipped : inventory_unit.line_item.quantity*inventory_unit.line_item.qty_per_pack
    amount_cost_price = qty_cancel * inventory_unit.variant.cost_price.to_i
    journal_entry = Journal::JournalEntry.create(description: "Cancel Order: #{inventory_unit.order.number} - #{qty_cancel} pcs X #{inventory_unit.variant.sku}", date: DateTime.now)
    # credit cost of sales
    Journal::JournalItem.create(account_id: @cost_of_sales, description: "Cancel Order: #{inventory_unit.order.number} - #{qty_cancel} pcs X #{inventory_unit.variant.sku}", credit: amount_cost_price, currency: "IDR", originator: inventory_unit, journal_entry_id: journal_entry.id)
    # debit inventory
    Journal::JournalItem.create(account_id: @inventory, description: "Cancel Order: #{inventory_unit.order.number} - #{qty_cancel} pcs X #{inventory_unit.variant.sku}", debit: amount_cost_price, currency: "IDR", originator: inventory_unit, journal_entry_id: journal_entry.id)
  end

  def refund_to_store_credit(inventory_units)
    return if !inventory_units.first.order.paid?
    order = inventory_units.first.order

    order.payments.store_credits.pending.each(&:void_transaction!)
    if order.payments.bank_transfers.completed.count > 0
      amount = 0
      order.payments.bank_transfers.completed.each do |payment|
        amount += payment.amount
      end
      if amount > 0
        order.user.store_credits.create!(amount: amount, category_id: 2, currency: "IDR", created_by: 
          Spree::StoreCredit.default_created_by, memo: "Cancelled product item in order ID #{order.number}", action_originator: order)
      end
    end

    order.payments.completed.each(&:cancel!)

    order.update!
    order.reload

    order.add_store_credit_payments_from_admin
    order.update!
  end
end

app/controllers/spree/admin/orders/customer_details_controller_decorator.rb
Spree::Admin::Orders::CustomerDetailsController.class_eval do
 
  def update
    if @order.contents.update_cart(order_params)

      if should_associate_user?
        requested_user = Spree.user_class.find(params[:user_id])
        @order.associate_user!(requested_user, @order.email.blank?)
      end
      @order.update_attributes(dropship_params) unless dropship_params.blank? || dropship_params.nil?
      unless @order.completed?
        @order.next
        @order.refresh_shipment_rates
      end

      flash[:success] = Spree.t('customer_details_updated')
      redirect_to edit_admin_order_url(@order)
    else
      render action: :edit
    end
       
  end   

  private

  def order_params
    params.require(:order).permit(
      :email,
      :use_billing,
      bill_address_attributes: permitted_address_attributes,
      ship_address_attributes: permitted_address_attributes
    )
  end
  def dropship_params
    params.permit(:dropship, :dropship_name, :dropship_phone, :notes)
  end
end

app/views/spree/admin/orders/_carton_manifest.html.erb
<% carton.manifest_for_order(order).each do |item| %>
  <tr class="stock-item" data-item-quantity="<%= item.quantity %>">
    <td class="item-image">
      <%= image_tag item.variant.display_image.attachment(:mini) %>
    </td>
    <td class="item-name">
      <%= item.variant.product.name %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
      <% if item.variant.sku.present? %>
        <strong><%= Spree::Variant.human_attribute_name(:sku) %>:</strong>
        <%= item.variant.sku %>
      <% end %>
    </td>
    <td class="item-price align-center"><%= item.line_item.single_money.to_html %></td>
    <td class="item-qty-show align-center">
        <% item.states.each do |state,count| %>
          <%= count %> x <%= Spree.t(state, scope: 'inventory_states') %>
        <% end %>
    </td>
    <td class="item-total align-center"><%= item.line_item.display_amount.to_html %></td>
  </tr>
<% end %>

app/views/spree/admin/orders/_line_items_edit_form.html.erb
<div data-hook="admin_order_form_fields">
  <% if @line_item.try(:errors).present? %>
      <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @line_item } %>
  <% end %>

  <%= render :partial => "spree/admin/orders/line_items", :locals => { :order => order } %>
  <%= render :partial => "spree/admin/orders/adjustments", :locals => {
          :adjustments => @order.line_item_adjustments,
          :order => order,
          :title => Spree.t(:line_item_adjustments)
  } %>
  <%= render :partial => "spree/admin/orders/adjustments", :locals => {
          :adjustments => @order.shipment_adjustments,
          :order => order,
          :title => Spree.t(:shipment_adjustments)
  } %>
  <%= render :partial => "spree/admin/orders/adjustments", :locals => {
          :adjustments => @order.adjustments,
          :order => order,
          :title => Spree.t(:order_adjustments)
  } %>

  <% if order.line_items.exists? %>
      <fieldset class="no-border-bottom" id="order-total" data-hook="order_details_total">
        <legend><%= Spree.t(:order_total) %></legend>
        <% if !order.preorder? %>
          <span class="order-total"><%= order.display_total %></span>
        <% else %>
          <span class="order-total"><%= order.display_subtotal_preorder %></span>
        <% end %>
      </fieldset>
  <% end %>

  <%= javascript_tag do -%>
      var order_number = '<%= @order.number %>';
      var shipments = [];

      <% @order.shipments.each do |shipment| %>
            shipments.push(<%== shipment.as_json(:root => false, :only => [:id, :tracking, :number, :state, :stock_location_id], :include => [:inventory_units, :stock_location]).to_json %>);
      <% end %>
  <% end -%>
</div>

app/views/spree/admin/orders/index.haml
- admin_breadcrumb(plural_resource_name(Spree::Order))
- content_for :page_actions do
  %li
    = button_link_to 'Download PO Order Pending', admin_download_pending_po_path
    = button_link_to 'Preorder', admin_orders_path(@search, :'q[preorder_eq]' => '1')
    = button_link_to 'Ready Stock', admin_orders_path(@search, :'q[preorder_eq]' => '0')
    = button_link_to Spree.t(:new_order), new_admin_order_url, :id => 'admin_new_order'
- end if can? :edit, Spree::Order.new
- content_for :table_filter_title do
  = Spree.t(:search)
- content_for :table_filter do
  .bootstrap-3
    %div{"data-hook" => "admin_orders_index_search"}
      = search_form_for [:admin, @search] do |f|
        .row
          .field-block.col-xs-3
            .date-range-filter.field
              = label_tag :q_created_at_gt, Spree.t(:date_range)
              .date-range-fields
                = f.text_field :created_at_gt, :class => 'datepicker datepicker-from', :value => params[:q][:created_at_gt], :placeholder => Spree.t(:start)
                %span.range-divider
                  %i.fa.fa-arrow-right
                = f.text_field :created_at_lt, :class => 'datepicker datepicker-to', :value => params[:q][:created_at_lt], :placeholder => Spree.t(:stop)
            -# .field
            -#   = label_tag :q_state_eq, Spree.t(:status)
            -#   = f.select :state_eq, Spree::Order.state_machines[:state].states.collect {|s| [Spree.t("order_state.#{s.name}"), s.value]}, {:include_blank => true}, :class => 'select2'
            .field{"data-hook" => "sku-select"}
              = label_tag :q_line_items_variant_id_in, "SKU"
              = f.text_field :line_items_variant_id_in, class: "variant_autocomplete fullwidth"
            .field
              = label_tag :preorder_eq, "Status Order"
              %br/
              = f.select :preorder_eq, [["Preorder", 1], ["Ready Stock", 0]], { include_blank: true }, { class: "select2" }
            -# .field
            -#   = label_tag nil, Spree.t(:promotion)
            -#   = f.text_field :promotions_codes_value_cont, :size => 25
            -# .field
            -#   = label_tag nil, Spree.t(:shipment_number)
            -#   = f.text_field :shipments_number_cont
          .col-xs-6
            .row
              .col-xs-6
                .field
                  = label_tag :q_number_cont, Spree.t(:order_number, :number => '')
                  = f.text_field :number_cont
                .field
                  = label_tag "Nominal Total"
                  = f.text_field :item_total_or_down_payment_total_eq
                .field
                  = label_tag :preorder_eq, "Status Payment"
                  %br/
                  = f.select :payment_state_eq, [["Pending", "balance_due"], ["Paid", "paid"], ["Cancel", "void"]], { include_blank: true, selected: params[:q][:payment_state_eq] }, { class: "select2" }
              .col-xs-6
                .field
                  = label_tag :q_email_cont, Spree.t(:email)
                  = f.text_field :email_cont
                .field
                  = label_tag :q_name_cont, "Member Name"
                  = f.text_field :user_name_cont
                .field
                  = label_tag :q_name_cont, "Confirmation Order"
                  %br/
                  = f.select :payment_confirmations_order_id_null, [["Yes", "0"], ["No", "1"]], { include_blank: true, selected: params[:q][:payment_confirmations_order_id_null] }, { class: "select2" }
              -# .col-xs-12
                -# .field{"data-hook" => "sku-select"}
                -#   = label_tag :q_line_items_variant_id_in, "SKU"
                -#   = f.text_field :line_items_variant_id_in, class: "variant_autocomplete fullwidth"
              -# .col-xs-12
                -# .field
                -#   = label_tag :q_name_cont, "Member Name"
                -#   = f.text_field :user_name_cont
          .col-xs-3
            -# - if Spree::Store.count > 1
            -#   .field
            -#     = label_tag nil, Spree.t(:store)
            -#     = f.select :store_id_eq, Spree::Store.all.map { |s| [s.name, s.id] }, { include_blank: true }, { class: "select2" }
            .field.checkbox
              %label
                = f.check_box :completed_at_not_null, {:checked => @show_only_completed}, '1', '0'
                = Spree.t(:show_only_complete_orders)
            .field
              = label_tag :lock_eq, "Status Order Lock"
              %br/
              = f.select :lock_eq, [["Lock", 1], ["Unlock", 0]], { include_blank: true, selected: params[:q][:lock_eq] }, { class: "select2" }
        .clearfix
        .actions.filter-actions
          %div{"data-hook" => "admin_orders_index_search_buttons"}
            = button Spree.t(:filter_results)
= paginate @orders, theme: "solidus_admin"
- if @orders.any?
  %table#listing_orders.index{"data-hook" => ""}
    %thead
      %tr{"data-hook" => "admin_orders_index_headers"}
        - if @show_only_completed
          %th.align-left= sort_link @search, :completed_at, "Date"
        - else
          %th.align-left= sort_link @search, :created_at, "Date"
        %th.align-left= sort_link @search, :number
        %th.align-left Customer Name
        %th.align-left= sort_link @search, :total
        / %th= sort_link @search, :state
        %th.align-left= sort_link @search, :payment_state
        - if Spree::Order.checkout_step_names.include?(:delivery)
          %th.align-left= sort_link @search, :shipment_state
        %th.align-left Order Type
        %th.actions{"data-hook" => "admin_orders_index_header_actions"}
    %tbody
      - @orders.each do |order|
        %tr{:class => "state-#{order.state.downcase} #{cycle('odd', 'even')}", "data-hook" => "admin_orders_index_rows"}
          %td= l (@show_only_completed ? order.completed_at : order.created_at).to_date
          - if order.preorder?
            %td= link_to order.number, spree.cart_admin_order_url(order)
          - else
            %td= link_to order.number, cart_admin_order_path(order)
          / %td
          /   %span{:class => "state #{order.state.downcase}"}= Spree.t("order_state.#{order.state.downcase}")
          %td
            -if order.user
              = order.user.name
            -else
              = order.email
          %td= order.preorder? ? number_to_currency(order.down_payment_total) : order.display_total.to_html
          %td
            %span{:class => "state #{order.payment_state}"}= link_to "#{order.payment_state_human}", admin_order_payments_path(order) if order.payment_state
          - if Spree::Order.checkout_step_names.include?(:delivery)
            %td
              - if order.shipment_state == "backorder"
                %span{:class => "state #{order.shipment_state}"}= "pending" if order.shipment_state
              - else
                %span{:class => "state #{order.shipment_state}"}= Spree.t("shipment_states.#{order.shipment_state}") if order.shipment_state
          %td
            = order.preorder? ? "Preorder" : "Ready Stock"
          / %td
          /   - if order.user
          /     = link_to order.email, edit_admin_user_path(order.user)
          /   - else
          /     = mail_to order.email
          %td.actions{"data-hook" => "admin_orders_index_row_actions"}
            = link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}", :no_text => true
            - if order.payment_state_human == "pending" || order.payment_state_human == "pending on dp"
              = link_to "", admin_order_payment_confirmation_new_path(order), class: 'fa fa-check-square icon_link with-tip no-text', "data-original-title" => "Payment Confirmation"
            - if order and order.completed_at?
              = link_to "", spree.admin_order_path(order, :pdf , :template => "invoice"), :class => "fa fa-print icon_link with-tip no-text", "data-original-title" => "Print"
            - if order.lock?
              = link_to "", admin_order_lock_unlock_path(order), class: 'fa fa-lock icon_link with-tip no-text', "data-original-title" => "Unlock Order!", data: {confirm: "Apakah anda yakin akan membuka order ini? jika order terbuka akan tampil ketika generate shipment"}
            - else
              = link_to "", admin_order_lock_unlock_path(order), class: 'fa fa-unlock icon_link with-tip no-text', "data-original-title" => "Lock Order!", data: {confirm: "Apakah anda yakin akan mengunci order ini? jika order terkunci tidak akan keluar ketika generate shipment"}
- else
  .col-xs-9.no-objects-found
    = render 'spree/admin/shared/no_objects_found', resource: Spree::Order, new_resource_url: spree.new_admin_order_path
= paginate @orders, theme: "solidus_admin"

app/views/spree/admin/orders/payment_confirmation_new.haml
= form_for @payment_confirmation, :url => admin_order_payment_confirmation_path(params[:id]), method: :put, html: {class: "form-horizontal"} do |f|
  .modal-header
    %h4#myModalLabel.modal-title Payment Confirmation Order #{params[:id]}
  .modal-body
    .form-group
      = f.label :bank_destination, "Transfer ke rekening", class: 'col-sm-3 control-label text-left'
      .col-sm-7.col-xs-10
        = f.collection_select :bank_destination, Spree::Bank.active , :name, Proc.new{|a|"#{a.name} (#{a.account_no})"}, {}, {class: 'select2 fullwidth'}
    .form-group
      = f.label :bank_sender, "Dari Bank", class: 'col-sm-3 control-label text-left'
      .col-sm-7.col-xs-10
        = f.text_field :bank_sender, class: 'form-control'
    .form-group
      = f.label :sender_name, "Nama Rekening Anda", class: 'col-sm-3 control-label text-left'
      .col-sm-7.col-xs-10
        = f.text_field :sender_name, class: 'form-control'
    .form-group
      = f.label :amount, "Jumlah Transfer", class: 'col-sm-3 control-label text-left'
      .col-sm-7.col-xs-10
        = f.text_field :amount, class: 'form-control'
    .form-group
      =f.label :transaction_date, "Tanggal Transfer", class: 'col-sm-3 control-label text-left'
      .col-sm-7.col-xs-10
        = f.date_field :transaction_date, class: 'form-control'
    .form-group
      = f.label :note, class: 'col-sm-3 control-label text-left'
      .col-sm-7.col-xs-10
        = f.text_field :note, class: "form-control"
    = f.hidden_field :user_id, value: current_spree_user.id
  .modal-footer
    = f.submit "Confirm", class: 'btn btn-pink'  

app/views/spree/admin/orders/show_inventory_unit.haml
- admin_breadcrumb(plural_resource_name(Spree::InventoryUnit))
- content_for :table_filter_title do
  = Spree.t(:search)
- content_for :table_filter do
  .bootstrap-3
    %div{"data-hook" => "admin_orders_index_search"}
      = search_form_for @q, url: admin_order_inventory_units_path do |f|
        .row
          .col-sm-6
            .field
              %label ORDER NUMBER
              = f.text_field :order_number_cont
          .col-sm-6
            .field
              %label SKU
              = f.text_field :variant_sku_cont
        .row
          .col-sm-12.text-center
            = f.submit "Search", class: "btn btn-success"

-if @inventory_units.present? 
  = paginate @inventory_units, theme: "solidus_admin" 
  %table
    %thead
      %tr
        %th Date
        %th Order Number
        %th SKU
        %th Status
        %th Free Stock Qty (pcs)
        %th Qty Order (pcs)
        %th Qty Order (pack)
        %th Qty Shipped (pcs)
    %tbody
      - @inventory_units.each do |iu|
        %tr
          %td= iu.created_at.to_date
          %td= iu.order.number
          %td= iu.variant.sku
          %td= iu.state_to_human
          %td= iu.variant.stock_items.first.real_qty_free_stock
          %td #{iu.total_pieces}
          %td #{iu.line_item.quantity}
          %td #{if iu.state == "shipped" then iu.shipped else "-" end}
          %td.actions
            - if iu.state == 'on_hand' || iu.state == 'backordered'
              = link_to "", admin_backordered_inventory_unit_path(iu), method: :put, class: "fa #{if iu.state == "on_hand" then "fa-product-hunt" else "fa-registered" end} icon_link with-tip no-text", "data-original-title" => "Mark as #{if iu.state == "on_hand" then "Pending" else "Ready" end}", :data => { :confirm => 'Are you sure you want to change state this unit to pending/ready?' }
  = paginate @inventory_units, theme: "solidus_admin" 
- else
  .alpha.twelve.columns.no-objects-found
    No Inventory Unit