config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  namespace :journal do
    resources :payment_store_credits do
      collection do
        put :use_store_credit_for_order
        put :use_store_credit_for_invoice
        put :use_store_credit_for_journal_invoice
      end
    end
    resources :store_credit_categories
    resources :purchase_invoices do
      member do
        get :add_items
        put :update_cart
        put :confirm
        get :paid
        get :refund
        put :refund_cart
        get :add_note
        put :update_note
        get :print
        get :reverse_to_draft
      end
    end
    resources :categories
    resources :accounts
    resources :reports do
      collection do
        get :trial_balance
        get :general_ledger
        get :balance_sheet
        get :transaction
        get :cash_and_bank
        get :profit_and_loss
        get :cash_flow_statement
      end
    end
    resources :transaction_rmbs
    resources :transactions do
      member do
        get :record_payment
        put :record_container
        put :record_order
        put :record_invoice
        put :record_purchase
        put :record_bill
        put :record_journal_invoice
        get :transfer
        put :transfer_fund
        put :add_store_credit
        get :history
        put :record_expense
        put :record_expense_transfer_fund
        put :record_income_transfer_fund
        get :add_counter_part
        put :counter_part
      end
      collection do
        put :use_store_credit_for_order
        put :use_store_credit_for_invoice
        get :show_import
        put :import
        get :all_payment_confirmed
      end
    end
    resources :transfer_funds
    resources :journal_items do
      collection do
        get :all_journal_entries
      end
    end
    resources :bills do
      member do 
        put :record_bill_rmb
        get :new_payment
        put :create_payment
      end
    end
    resources :invoices do
      member do
        get :record_invoice
        put :record_order_invoice
        put :record_invoice_cn
        get :reminder_email
        put :unpay
      end
    end
    resources :info_payments do 
      member do
        get :confirmed 
      end
    end
    resources :store_credits do
      collection do
        get :cash_out_new
        put :create_cash_out
        get :cash_out_request
        get :bill_paid
      end
    end
  end

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
    namespace :admin do
      get 'stock_items/card_stock', to: "stock_items#card_stock"
      get 'stock_items/:id/stock_movement', to: "stock_items#stock_movement", as: :stock_item_movement
      get 'stock_items/:id/stock_warehouse_movement', to: "stock_items#stock_warehouse_movement",  as: :stock_warehouse_movement
      get 'products/:id/view_buyer', to: "products#view_buyer", as: :view_buyer
      get 'products/:id/hide_show_product', to: "products#hide_show_product", as: :hide_show_product
      put 'orders/:id/payment_confirmation', to: "orders#payment_confirmation", as: :order_payment_confirmation
      get 'orders/:id/payment_confirmation_new', to: "orders#payment_confirmation_new", as: :order_payment_confirmation_new
      get 'orders/:id/lock_unlock', to: "orders#lock_unlock", as: :order_lock_unlock
      get 'orders/return_request', to: "orders#return_request", as: :customer_return_request
      get 'orders/show_inventory_unit', to: "orders#show_inventory_unit", as: :order_inventory_units
      put 'orders/:id/inventory_unit', to: "orders#backordered_inventory", as: :backordered_inventory_unit
      get 'orders/download_pending_po', to: "orders#download_pending_po", as: :download_pending_po
      get 'shipping_methods/:id/download_rates', to: "shipping_methods#download_rates", as: :download_rates
      resources :cash_out_requests do
        collection do
          get :cash_out_new
          put :create_cash_out
        end
      end
      resources :reports do
        collection do
          get :sales_ready_stock
          get :income_dp_preorder
          get :unpaid_invoice
          get :invoice_sales
          get :return_order
          get :store_credit
          get :lost_item
          get :dp_hangus
          get :cek_stock
          get :credit_note
        end
      end
      resources :return_to_suppliers do
        member do
          get :items
          put :return
          put :update_return
          put :confirm
          put :credit_to_supplier
          put :treat_as_expense
          put :ship
          put :create_invoice
        end
        collection do
          get :delete_item
        end
      end

      resources :inventory_adjustments do
        member do
          put :update_items
          put :add_item
          get :validate
        end
        collection do
          get :item_destroy
        end
      end

      resources :inventory_adjustment_categories
      # get 'reports/sales_ready_stock', to: "reports#sales_ready_stock"
      resources :price_levels
      resources :purchase_orders do
        member do
          get :items
          put :update_items
          get :payment
          get :shipment
          put :confirm
          put :add_item
          get :cart
          get :print
          get :reverse_to_pending
          get :update_after_change_item
        end
        collection do
          get :po_pending
          get :line_item_destroy
          get :all
          get :mark_completed
        end
      end
      resources :containers do
        member do
          get :new_item
          put :update_items
          put :receive_items
        end
        collection do
          get :selisih_barang
        end
      end
      resources :container_items do
        member do
          get :ready
          put :complete
          put :refund
          put :generate_po
          get :reverse
          get :delete_item
          put :treat_as_expense
        end
      end
      resources :invoices do
        member do
          get :items
          put :select_items
          get :confirm
          put :send_invoice
          get :completed
          put :dp_angus
          put :add_note
          put :flag_dropship
          get :reminder_email
          get :lock_unlock
          get :payment_confirmation_new
          put :payment_confirmation
        end
        collection do
          get :generate_invoice
        end
      end
      resources :invoice_items do
        member do
          patch :change_address
          put :add_adjustment
        end
      end

      resources :shipment_groups do
        member do
          put :update_inventory_unit
          get :ready
          get :print
          get :processing
          put :packed
          put :ship
        end
        collection do
          get :generate_shipment_group
        end
      end
      resources :news
      resources :testimonials do
        member do
          get :publish
        end
      end
      put 'new_address', to: "invoices#new_address"
    resources :shipments do
      member do
        put :ship
        put :mark_as_shipped
      end
    end
    end
    resources :testimonials
    resources :payment_confirmations
    resources :shipping_rates do
      collection do
        put :check_shipping_rate
        get :show_shipping_rate
      end
    end
    resources :cash_out_requests
    resources :return_authorization_users do 
      member do
        get :new_rma
      end
      collection do
        get :shipped_order
      end
    end
    get 'products/new_items', to: "products#new_items"
    get 'products/ready_stock', to: "products#ready_stock"
    get 'products/album', to: "products#album"
    get 'products/sale', to: "products#sale"
    put 'home/new_address', to: "home#new_address"
    get 'home/addresses', to: "home#addresses", as: :user_addresses
    get 'store_credits/:id', to: "home#store_credit"
    get 'invoice/:id', to: "home#invoice", as: :user_invoice
    get 'order/show/:id', to: "home#show_order", as: :user_order_show
    get 'invoice/:id/print', to: "home#print", as: :user_invoice_print
    get 'orders/:id/print', to: "orders#print", as: :orders_print
    get 'products/album/:id/show_album_image', to: "products#show_album_image", as: :show_album_product_image

    # buat bayar invoice pake store credit di my account
    get 'invoice/pay_with_sc/:id', to: "home#use_sc_for_invoice_po", as: :pay_sc_inv_po
    put 'invoice/pay_with_sc/:id', to: "home#pay_with_sc_invoice", as: :use_sc_inv_po

    # buat bayar order pake store credit di my account
    get 'order/pay_with_sc/:id', to: "home#use_sc_for_order", as: :pay_sc_order
    put 'order/pay_with_sc/:id', to: "home#pay_with_sc_order", as: :use_sc_order

    # buat bayar invoice_journal(credit) pake store credit di my account
    get 'credit/pay_with_sc/:id', to: "home#use_sc_for_credit", as: :pay_sc_credit
    put 'credit/pay_with_sc/:id', to: "home#pay_with_sc_credit", as: :use_sc_credit

    #ubah ekspedisi di invoice
    put 'invoice/ubah_ekspedisi/:id', to: "home#ubah_ekspedisi", as: :ubah_ekspedisi_user

  end
end

app/controllers/spree/admin/purchase_orders_controller.rb
module Spree
  module Admin
    class PurchaseOrdersController < ResourceController

      def all
        @search = Spree::PurchaseLineItem.ransack(params[:q]) 
        @purchase_order_lines = @search.result.joins(:purchase_order).where("spree_purchase_orders.payment_state != ?", "cart").page(params[:page]).per(params[:per_page])
      end

      def index
        @purchase_orders = Spree::PurchaseOrder.filter(params.slice(:start_date, :end_date, :supplier_id_is, :shipment_is, :payment_is, :sku_contain, :id_is)).where("spree_purchase_orders.payment_state != ?", "cart").order("created_at DESC").page params[:page]
      end

      def new
        @suppliers = Spree::Supplier.all
        invoke_callbacks(:new_action, :before)
        respond_with(@object) do |format|
          format.html { render layout: !request.xhr? }
          if request.xhr?
            format.js   { render layout: false }
          end
        end
      end

      def cart
        @items = Spree::PurchaseLineItem.where("purchase_order_id = ? AND quantity > ?", @purchase_order.id, 0).includes(:variant).order("spree_variants.sku ASC")
      end

      def create
        invoke_callbacks(:create, :before)
        @object.attributes = permitted_resource_params
        if @object.save
          invoke_callbacks(:create, :after)
          # flash[:success] = flash_message_for(@object, :successfully_created)
          respond_with(@object) do |format|
            format.html { redirect_to items_admin_purchase_order_path(@object) }
            format.js   { render layout: false }
          end
        else
          invoke_callbacks(:create, :fails)
          respond_with(@object) do |format|
            format.html do
              @suppliers = Spree::Supplier.all
              flash.now[:error] = @object.errors.full_messages.join(", ")
              render_after_create_error
            end
            format.js { render layout: false }
          end
        end
      end

      def items
        @user = spree_current_user
        @suppliers = Spree::Supplier.all
        @items = @object.items.includes(:variant).filter(params.slice(:name_contain, :sku_contain, :zero_cost_price)).order("spree_variants.sku ASC")
        @items_purchase = @object.items.filter(params.slice(:name_contain, :sku_contain, :zero_cost_price))
        @products = @object.supplier.products.all
        @variants = Spree::Variant.where(product_id: @products.pluck(:id)).where.not(id: @items_purchase.pluck(:variant_id))
      end

      def confirm
        @object.confirm!
        flash[:success] = "Purchase Order has been confirmed."
        redirect_to cart_admin_purchase_order_path(@object)
      end

      def update_items
        unless @object.confirmed?
          params[:item_quantity].each do |key, value|
            next if value.to_i <= 0
            line = Spree::PurchaseLineItem.find_by_id key
            if line
              line.quantity = value
              line.save
            end
          end
        end
        params[:cost_price].each do |key, value|
          next if value.to_i <= 0
          line = Spree::PurchaseLineItem.find_by_id key
          if line
            line.cost_price = value
            line.save
            variant = line.variant
            if variant
              variant.cost_price = value
              variant.save
            end
          end
        end
        flash[:success] = "Item has been updated"
        @object.pending! if @object.cart?
        @object.recalculate if @object.confirmed?
        redirect_to items_admin_purchase_order_path(@object)
      end

      def po_pending
        @purchase_orders = Spree::PurchaseOrder.shipment_pending.order(:created_at).page params[:page]
      end

      def add_item
        variant = Spree::Variant.find_by_id(params[:add_item][:variant_id])
        create_item = @object.create_item(variant)
        if create_item
          flash[:success] = "Items Purchase Order was successfully created."
          redirect_to request.referrer
        else
          flash[:danger] = "Add Items Purchase Order failed."
          redirect_to request.referrer
        end
      end

      def line_item_destroy
        item = Spree::PurchaseLineItem.find_by_id(params[:item])
        po = Spree::PurchaseOrder.find_by_id(params[:po])
        if item.destroy
          po.recalculate
          flash[:success] = "Item was successfully deleted."
          redirect_to request.referrer
        else
          flash[:danger] = "Delete Purchase Item failed"
          redirect_to request.referrer
        end
      end

      def print
        @purchase_order = @object
        @items = Spree::PurchaseLineItem.where("purchase_order_id = ? AND quantity > ?", @purchase_order.id, 0).includes(:variant).order("spree_variants.sku ASC")
      end

      def mark_completed
        line_item = Spree::PurchaseLineItem.find_by_id(params[:line_item_id])
        if line_item.mark_completed(whodunnit)
          flash[:success] = "Items Purchase Order was successfully completed."
          redirect_to request.referrer
        else
          flash[:danger] = "Sorry something went wrong"
          redirect_to request.referrer
        end
      end

      def reverse_to_pending
        if @object.reverse_po_to_pending
          flash[:success] = "Successfully reverse status to pending"
          redirect_to request.referrer
        else
          flash[:danger] = "Sorry something went wrong"
          redirect_to request.referrer
        end
      end

      def update_after_change_item
        if @object.items.collect{|x| x.update_after_change_item}
          flash[:success] = "Successfully update total items"
          redirect_to request.referrer
        else
          flash[:danger] = "Sorry something went wrong"
          redirect_to request.referrer
        end
      end

      private

      def items_params
        params.require(:purchase_order).permit(items_attributes: [:quantity])
      end

      def whodunnit
        spree_current_user
      end

    end
  end
end

app/views/spree/admin/purchase_orders/all.haml
- admin_breadcrumb(plural_resource_name(Spree::PurchaseOrder))

- content_for :table_filter do
  %div
    = search_form_for @search, url: all_admin_purchase_orders_path(@purchase_order_lines) do |f|
      - locals = {:f => f}
      .row
        .col-xs-4
          .field
            = f.label :variant_sku_cont, "Code Item"
            = f.text_field :variant_sku_cont, :size => 15
        .col-xs-4
          .field
            = f.label :purchase_order_id_eq, "Purchase ID"
            = f.text_field :purchase_order_id_eq, :size => 15
        .col-xs-4
          .form-group.form-group-default
            = f.label :payment_state_eq, "Payment Status"
            = f.select :payment_state_eq, options_for_select([["Paid", "paid"], ["Partially Paid", "partially_paid"], ["Pending", "pending"]]), {include_blank: true}, :class => "form-control select2", prompt: "Choose one"
      .row
        .col-xs-4
          .form-group.form-group-default
            = f.label :shipment_status_eq, "Shipment Status"
            = f.select :shipment_status_eq, options_for_select([["Pending", "pending"], ["Shipped", "shipped"], ["In Completed", "in_completed"],["Completed", "completed"]]), {include_blank: true}, :class => "form-control select2", prompt: "Choose one"
        .col-xs-4
          .form-group.form-group-default
            = f.label :purchase_order_supplier_id_eq, "Supplier"
            = f.select :purchase_order_supplier_id_eq, options_from_collection_for_select(Spree::Supplier.all, :id, :name), {:include_blank => true}, :class => "form-control select2", prompt: "Choose one"
      .actions.filter-actions
        = button Spree.t(:search)

= paginate @purchase_order_lines, theme: "solidus_admin" 
%table
  %thead
    %tr.to_icon
      %th.align-left{width: "12%"} Created at
      %th.align-left{width: "3%"} PO ID
      %th.align-left{width: "8%"} Supplier
      %th.align-left{width: "5%"} Image
      %th.align-left{width: "14%"} Code Item
      %th.align-left{width: "5%"} Qty
      %th.align-left{width: "5%"} Isi
      %th.align-left{width: "5%"} Total Pcs
      - if spree_current_user.admin?
        %th.align-left{width: "10%"} Price 
        %th.align-left{width: "10%"} Total Price
      %th.align-left{width: "5%"} Payment
      %th.align-left{width: "10%"} Delivery
      %th.align-left{width: "5%"} Pcs Received
      %th.align-left{width: "5%"} Container ID
  %tbody
    - @purchase_order_lines.each do |line|
      %tr
        %td= line.purchase_order.created_at.to_date
        %td= link_to line.purchase_order.id, items_admin_purchase_order_path(line.purchase_order)
        %td= line.purchase_order.supplier.name
        %td= image_tag line.variant.display_image.attachment(:mini)
        %td= line.variant.sku
        %td= line.quantity
        %td= line.variant.product.total_items
        %td= line.items
        - if spree_current_user.admin?
          %td= number_to_multi_currency(line.cost_price, line.currency)
          %td= number_to_multi_currency(line.total, line.currency)
        %td= line.payment_state.humanize
        %td
          - if line.completed? && line.completed_by.present?
            - user = Spree::User.find_by_id(line.completed_by)
            #{line.shipment_status.humanize} by #{user.name.blank? ? user.email : user.name}
          - else
            = line.shipment_status.humanize
        %td= line.total_received
        %td
          %ul
            - line.container_items.each do |c|
              %li= link_to c.container.id, admin_container_path(c.container)
        %td.actions
          - if line.shipment_status != "completed"
            = link_to_with_icon 'check', "Mark as Complete", mark_completed_admin_purchase_orders_path(line_item_id: line.id), :no_text => true, method: :get
  %tfooter
    %tr
      %td{colspan: 3}
      %td{colspan: 2} Total Qty:
      %td #{@purchase_order_lines.sum(:quantity)}
      %td Total Pcs
      %td #{@purchase_order_lines.sum(:items)}
      - if spree_current_user.admin?
        %td{colspan: 2} #{number_to_delimited(@purchase_order_lines.sum(:total))}
      %td{colspan: 2}
      %td #{@purchase_order_lines.sum(&:total_received)}
= paginate @purchase_order_lines, theme: "solidus_admin" 

app/views/spree/admin/purchase_orders/index.haml
- admin_breadcrumb(plural_resource_name(Spree::PurchaseOrder))

- content_for :page_actions do
  %li
    = button_link_to "New Purchase Order", new_admin_purchase_order_url(@purchase_order)
= form_for('Filter_purchase', :as => 'filter_purchase', method: :get, :url => admin_purchase_orders_path) do |f|
  .row 
    .col-sm-3
      .form-group.form-group-default.required
        %label Start Date
        = date_field_tag 'start_date', nil, class: 'form-control'
    .col-sm-3
      .form-group.form-group-default.required
        %label End Date
        = date_field_tag 'end_date', nil,class: 'form-control'
    .col-sm-3
      .form-group.form-group-default.required
        %label SKU
        = text_field_tag 'sku_contain', nil,class: 'form-control'
    .col-sm-3
      .form-group.form-group-default.required
        %label ID
        = text_field_tag 'id_is', nil,class: 'form-control'
  .row 
    .col-sm-3
      .form-group.form-group-default.required
        %label Payment Status
        = select_tag 'payment_is', options_for_select([["Paid", "paid"], ["Pending", "pending"], ["Confirmed", "confirmed"]]), {class: "form-control", :class => "select2", prompt: "Select Payment Status"}
    .col-sm-3
      .form-group.form-group-default.required
        %label Shipment Status
        = select_tag 'shipment_is', options_for_select([["Shipped", "shipped"], ["Pending", "pending"]]), {class: "form-control", :class => "select2", prompt: "Select Shipment Status"}
    .col-sm-3
      .form-group.form-group-default.required
        %label Supplier Name
        = select_tag :supplier_id_is, options_from_collection_for_select(Spree::Supplier.all, :id, :name), { :class => 'select2', style: "width: 100%", prompt: "Select Supplier"}
    .col-sm-3
      = f.submit "Search", class: "btn btn-success"

= paginate @purchase_orders, theme: "solidus_admin" 
%table
  %thead
    %tr
      %th.align-left Created at
      %th.align-left ID
      %th.align-left Supplier
      -if spree_current_user.admin?
        %th.align-left Amount
      %th.align-left Payment Status
      %th.align-left Shipping Status
      %th.align-left Notes
  %tbody
    - @purchase_orders.each do |po|
      %tr
        %td= po.created_at.to_date
        %td
          - if po.pending_payment? || po.confirmed?
            = link_to po.id, items_admin_purchase_order_path(po)
          - else
            = link_to po.id, cart_admin_purchase_order_path(po)
        %td= po.supplier.name
        -if spree_current_user.admin?
          - if !po.items.empty?
            %td= number_to_multi_currency(po.total, po.items.first.currency)
          - else
            %td= po.total.to_i
        %td= po.payment_state.humanize
        %td= po.shipping_state.humanize
        %td= po.notes
        - if spree_current_user.admin?
          %td.actions
            - if po.payment_state == "confirmed"
              = link_to "", print_admin_purchase_order_path(po, :pdf), class: 'fa fa-print icon_link with-tip no-text', "data-original-title" => "Print"
              = link_to "", reverse_to_pending_admin_purchase_order_path(po), class: 'fa fa-undo icon_link with-tip no-text', "data-original-title" => "Reverse to Pending", data: { confirm: "Apakah anda yakin akan mengembalikan status menjadi pending?"}
            - if po.payment_state == "pending" && can?(:delete, po)
              = link_to_delete po, :no_text => true
= paginate @purchase_orders, theme: "solidus_admin" 

app/views/spree/admin/purchase_orders/items.haml
- admin_breadcrumb("PO #{@purchase_order.supplier.name}")

%br
- content_for :page_actions do
  %li= button_link_to "Update Items From Product", update_after_change_item_admin_purchase_order_path(@purchase_order), data: {confirm: "Are you sure, you want to update items from product?"}
  %li= button_link_to "View Cart", cart_admin_purchase_order_path

%fieldset{"data-hook" => "new_product"}
  = form_for('filter_item', :as => 'filter_item', method: :get, :url => items_admin_purchase_order_path(@purchase_order)) do |a|
    .row 
      .col-sm-4
        .form-group.form-group-default.required
          %label Name
          = text_field_tag 'name_contain', nil, class: 'form-control'
      .col-sm-4
        .form-group.form-group-default.required
          %label SKU
          = text_field_tag 'sku_contain', nil, class: 'form-control'
      / .col-sm-4
      /   .form-group.form-group-default.required
      /     = select_tag 'zero_cost_price', options_for_select([["Cost Price 0", 0]]), {class: "form-control", :class => "select2", prompt: "Select Cost Price"}
    -# .row 
    -#   .col-sm-3
    -#     .form-group.form-group-default.required
    -#       %label Payment Status
    -#       = select_tag 'payment_is', options_for_select([["Paid", "paid"], ["Pending", "pending"], ["Confirmed", "confirmed"]]), {class: "form-control", :class => "select2", prompt: "Select Payment Status"}
    -#   .col-sm-3
    -#     .form-group.form-group-default.required
    -#       %label Shipment Status
    -#       = select_tag 'shipment_is', options_for_select([["Shipped", "shipped"], ["Pending", "pending"]]), {class: "form-control", :class => "select2", prompt: "Select Shipment Status"}
    -#   .col-sm-3
    -#     .form-group.form-group-default.required
    -#       %label SKU is
    -#       = a.collection_select(:sku_is, @items, :id, :name, {:prompt => 'Select Supplier'}, { :class => 'select2', style: "width: 100%" })
    .row 
      .align-center.col-sm-12
        = a.submit "Search", class: "btn btn-success"
= render :partial => 'spree/shared/error_messages', :locals => { :target => @purchase_order }
%fieldset
  %legend{:align => "center"} Product Items
  - if @purchase_order.pending_payment?
    .align-center
      %button.button{"data-toggle" => "modal", "data-target" => "#add-products"} Tambah Produk Lainnya
  = form_for [:admin, @purchase_order], method: :post, url: update_items_admin_purchase_order_path, :html => { :multipart => true } do |f|
    #items{style: "margin-top: 15px;"}
      = form_tag update_items_admin_purchase_order_path, method: :put do
        %table
          %thead
            %tr
              %th Image
              %th SKU
              %th PO
              %th DP Confirm
              %th Qty Pack
              %th Items per Pack
              %th Total Items
              - if @user.admin?
                %th Cost Currency
                %th Cost Price
                %th Total Cost Price
          %tbody
            - total_po_2 = 0
            - total_item_dp_confirm = 0
            - total_qty_pack = 0
            - total_items_all = 0
            - @items.each do |item|
              - total_order_in_pack = item.variant.stock_items.sum(:count_on_hand) / item.variant.product.total_items * -1
              - total_po_2 += total_order_in_pack
              - total_item_dp_confirm += item.dp_confirm.to_i
              - total_qty_pack += item.quantity
              - total_items_all += item.items
              %tr{id: "item_#{item.id}"}
                %td.align-center= image_tag item.variant.display_image.attachment(:mini)
                %td.align-center= item.variant.sku
                %td.align-center= total_order_in_pack
                %td.align-center= item.dp_confirm
                %td.align-center= text_field_tag "item_quantity[#{item.id}]", item.quantity, disabled: @purchase_order.confirmed? , class: "qty-pack", data: {"item-id" => "#{item.id}", "item-per-pack" => "#{item.variant.product.total_items}"}
                %td.align-center= item.variant.product.total_items
                %td.align-center= text_field_tag "total_items[#{item.id}]", item.items, id: "total_items_#{item.id}", disabled: true
                - if @user.admin?
                  %td.align-center= item.currency
                  %td.align-center= text_field_tag "cost_price[#{item.id}]", item.cost_price, class: "cost-price", data: {"item-id" => "#{item.id}", "item-per-pack" => "#{item.variant.product.total_items}"}
                  %td.total-cost-price.align-center= text_field_tag "total_cost_price[#{item.id}]", item.total, id: "total_cost_#{item.id}", class: "total_cost_price", disabled: true
                - else
                  = hidden_field_tag "cost_price[#{item.id}]", item.cost_price, class: "cost-price", data: {"item-id" => "#{item.id}", "item-per-pack" => "#{item.variant.product.total_items}"}
          - if @user.admin?
            %tfooter
              %tr
                %td.align-right{colspan: 2} TOTAL
                %td.align-center #{total_po_2}
                %td.align-center #{total_item_dp_confirm}
                %td.align-center #{total_qty_pack}
                %td.align-center
                %td.align-center #{total_items_all}
                %td.align-center
                %td.align-center= text_field_tag "total_po", @purchase_order.total, id: "total_po", disabled: true
        .align-center
          - if @purchase_order.pending_payment? || @purchase_order.confirmed?
            = submit_tag "Update Items"
#add-products.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title Add Items
      .modal-body
        .panel-body
          = form_for "add_item", :url => add_item_admin_purchase_order_path(params[:id]), method: :put, html: {class: 'the-form-modal'} do |a|
            .form-group.form-group-default.required
              = a.label "Products"
              = a.collection_select(:variant_id, @variants, :id, :sku, { :include_blank => Spree.t('match_choices.none') }, { :class => 'select2', style: "width: 100%" })
            .actions
              = a.submit 'Submit', class: "btn btn-success"

:javascript
  $("input.qty-pack").on("input", function(e){
    var qty_pack = Number(e.target.value);
    var id = $(this).data("item-id");
    var items_per_pack = Number($(this).data("item-per-pack"));
    var cost_price = $("#cost_price_" + id).val()
    var total_item = qty_pack * items_per_pack


    $("#total_items_" + id).val(total_item);
    $("#total_cost_" + id).val(total_item * cost_price);

    var sum = 0;
    $('.total_cost_price').each(function() {
        var price = $(this);
        sum += parseInt(price.val())
    });

    $('#total_po').val(sum);
  })
  $("input.cost-price").on("input", function(e){
    var cost_price = Number(e.target.value);
    var id = $(this).data("item-id");
    var items_per_pack = Number($(this).data("item-per-pack"));
    var qty_pack = $("#item_quantity_" + id).val();
    var total_item = qty_pack * items_per_pack

    $("#total_items_" + id).val(total_item);
    $("#total_cost_" + id).val(total_item * cost_price);

    var sum = 0;
    $('.total_cost_price').each(function() {
        var price = $(this);
        sum += parseInt(price.val())
    });

    $('#total_po').val(sum);
  })

app/views/spree/admin/purchase_orders/new.haml
= render :partial => 'spree/shared/error_messages', :locals => { :target => @purchase_order }
= form_for [:admin, @purchase_order], method: :post, url: admin_purchase_orders_path, :html => { :multipart => true } do |f|
  %fieldset{"data-hook" => "new_product"}
    %legend{:align => "center"} New Purchase Order
    = f.field_container :supplier do
      = f.label :supplier, class: 'required'
      %br/
      = f.collection_select(:supplier_id, @suppliers, :id, :name, { :include_blank => Spree.t('match_choices.none') }, { :class => 'select2', style: "width: 100%" })
      = f.error_message_on :supplier
    = render :partial => 'spree/admin/shared/new_resource_links'