config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  namespace :journal do
    resources :payment_store_credits do
      collection do
        put :use_store_credit_for_order
        put :use_store_credit_for_invoice
        put :use_store_credit_for_journal_invoice
      end
    end
    resources :store_credit_categories
    resources :purchase_invoices do
      member do
        get :add_items
        put :update_cart
        put :confirm
        get :paid
        get :refund
        put :refund_cart
        get :add_note
        put :update_note
        get :print
        get :reverse_to_draft
      end
    end
    resources :categories
    resources :accounts
    resources :reports do
      collection do
        get :trial_balance
        get :general_ledger
        get :balance_sheet
        get :transaction
        get :cash_and_bank
        get :profit_and_loss
        get :cash_flow_statement
      end
    end
    resources :transaction_rmbs
    resources :transactions do
      member do
        get :record_payment
        put :record_container
        put :record_order
        put :record_invoice
        put :record_purchase
        put :record_bill
        put :record_journal_invoice
        get :transfer
        put :transfer_fund
        put :add_store_credit
        get :history
        put :record_expense
        put :record_expense_transfer_fund
        put :record_income_transfer_fund
        get :add_counter_part
        put :counter_part
      end
      collection do
        put :use_store_credit_for_order
        put :use_store_credit_for_invoice
        get :show_import
        put :import
        get :all_payment_confirmed
      end
    end
    resources :transfer_funds
    resources :journal_items do
      collection do
        get :all_journal_entries
      end
    end
    resources :bills do
      member do 
        put :record_bill_rmb
        get :new_payment
        put :create_payment
      end
    end
    resources :invoices do
      member do
        get :record_invoice
        put :record_order_invoice
        put :record_invoice_cn
        get :reminder_email
        put :unpay
      end
    end
    resources :info_payments do 
      member do
        get :confirmed 
      end
    end
    resources :store_credits do
      collection do
        get :cash_out_new
        put :create_cash_out
        get :cash_out_request
        get :bill_paid
      end
    end
  end

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
    namespace :admin do
      get 'stock_items/card_stock', to: "stock_items#card_stock"
      get 'stock_items/:id/stock_movement', to: "stock_items#stock_movement", as: :stock_item_movement
      get 'stock_items/:id/stock_warehouse_movement', to: "stock_items#stock_warehouse_movement",  as: :stock_warehouse_movement
      get 'products/:id/view_buyer', to: "products#view_buyer", as: :view_buyer
      get 'products/:id/hide_show_product', to: "products#hide_show_product", as: :hide_show_product
      put 'orders/:id/payment_confirmation', to: "orders#payment_confirmation", as: :order_payment_confirmation
      get 'orders/:id/payment_confirmation_new', to: "orders#payment_confirmation_new", as: :order_payment_confirmation_new
      get 'orders/:id/lock_unlock', to: "orders#lock_unlock", as: :order_lock_unlock
      get 'orders/return_request', to: "orders#return_request", as: :customer_return_request
      get 'orders/show_inventory_unit', to: "orders#show_inventory_unit", as: :order_inventory_units
      put 'orders/:id/inventory_unit', to: "orders#backordered_inventory", as: :backordered_inventory_unit
      get 'orders/download_pending_po', to: "orders#download_pending_po", as: :download_pending_po
      get 'shipping_methods/:id/download_rates', to: "shipping_methods#download_rates", as: :download_rates
      resources :cash_out_requests do
        collection do
          get :cash_out_new
          put :create_cash_out
        end
      end
      resources :reports do
        collection do
          get :sales_ready_stock
          get :income_dp_preorder
          get :unpaid_invoice
          get :invoice_sales
          get :return_order
          get :store_credit
          get :lost_item
          get :dp_hangus
          get :cek_stock
          get :credit_note
        end
      end
      resources :return_to_suppliers do
        member do
          get :items
          put :return
          put :update_return
          put :confirm
          put :credit_to_supplier
          put :treat_as_expense
          put :ship
          put :create_invoice
        end
        collection do
          get :delete_item
        end
      end

      resources :inventory_adjustments do
        member do
          put :update_items
          put :add_item
          get :validate
        end
        collection do
          get :item_destroy
        end
      end

      resources :inventory_adjustment_categories
      # get 'reports/sales_ready_stock', to: "reports#sales_ready_stock"
      resources :price_levels
      resources :purchase_orders do
        member do
          get :items
          put :update_items
          get :payment
          get :shipment
          put :confirm
          put :add_item
          get :cart
          get :print
          get :reverse_to_pending
          get :update_after_change_item
        end
        collection do
          get :po_pending
          get :line_item_destroy
          get :all
          get :mark_completed
        end
      end
      resources :containers do
        member do
          get :new_item
          put :update_items
          put :receive_items
        end
        collection do
          get :selisih_barang
        end
      end
      resources :container_items do
        member do
          get :ready
          put :complete
          put :refund
          put :generate_po
          get :reverse
          get :delete_item
          put :treat_as_expense
        end
      end
      resources :invoices do
        member do
          get :items
          put :select_items
          get :confirm
          put :send_invoice
          get :completed
          put :dp_angus
          put :add_note
          put :flag_dropship
          get :reminder_email
          get :lock_unlock
          get :payment_confirmation_new
          put :payment_confirmation
        end
        collection do
          get :generate_invoice
        end
      end
      resources :invoice_items do
        member do
          patch :change_address
          put :add_adjustment
        end
      end

      resources :shipment_groups do
        member do
          put :update_inventory_unit
          get :ready
          get :print
          get :processing
          put :packed
          put :ship
        end
        collection do
          get :generate_shipment_group
        end
      end
      resources :news
      resources :testimonials do
        member do
          get :publish
        end
      end
      put 'new_address', to: "invoices#new_address"
    resources :shipments do
      member do
        put :ship
        put :mark_as_shipped
      end
    end
    end
    resources :testimonials
    resources :payment_confirmations
    resources :shipping_rates do
      collection do
        put :check_shipping_rate
        get :show_shipping_rate
      end
    end
    resources :cash_out_requests
    resources :return_authorization_users do 
      member do
        get :new_rma
      end
      collection do
        get :shipped_order
      end
    end
    get 'products/new_items', to: "products#new_items"
    get 'products/ready_stock', to: "products#ready_stock"
    get 'products/album', to: "products#album"
    get 'products/sale', to: "products#sale"
    put 'home/new_address', to: "home#new_address"
    get 'home/addresses', to: "home#addresses", as: :user_addresses
    get 'store_credits/:id', to: "home#store_credit"
    get 'invoice/:id', to: "home#invoice", as: :user_invoice
    get 'order/show/:id', to: "home#show_order", as: :user_order_show
    get 'invoice/:id/print', to: "home#print", as: :user_invoice_print
    get 'orders/:id/print', to: "orders#print", as: :orders_print
    get 'products/album/:id/show_album_image', to: "products#show_album_image", as: :show_album_product_image

    # buat bayar invoice pake store credit di my account
    get 'invoice/pay_with_sc/:id', to: "home#use_sc_for_invoice_po", as: :pay_sc_inv_po
    put 'invoice/pay_with_sc/:id', to: "home#pay_with_sc_invoice", as: :use_sc_inv_po

    # buat bayar order pake store credit di my account
    get 'order/pay_with_sc/:id', to: "home#use_sc_for_order", as: :pay_sc_order
    put 'order/pay_with_sc/:id', to: "home#pay_with_sc_order", as: :use_sc_order

    # buat bayar invoice_journal(credit) pake store credit di my account
    get 'credit/pay_with_sc/:id', to: "home#use_sc_for_credit", as: :pay_sc_credit
    put 'credit/pay_with_sc/:id', to: "home#pay_with_sc_credit", as: :use_sc_credit

    #ubah ekspedisi di invoice
    put 'invoice/ubah_ekspedisi/:id', to: "home#ubah_ekspedisi", as: :ubah_ekspedisi_user

  end
end

app/models/spree/container.rb
module Spree
  class Container < Spree::Base
    include Filterable
    validates :name, :delivery_orders, :delivery_date, :sack, :cbm, presence: true
    validates :name, :delivery_orders, uniqueness: true

    has_many :items, class_name: "Spree::ContainerItem", dependent: :destroy
    belongs_to :transaction_id, class_name: "Journal::Transaction"
    belongs_to :supplier, class_name: "Spree::Supplier"

    scope :name_user, -> (name){where("name like ?", "%#{name}%")}
    scope :id_is, -> (id_value){where(id: id_value)}
    scope :sku_contain, -> (sku) {joins(items: :variant).where("spree_variants.sku like ?", "%#{sku}%")}

    self.whitelisted_ransackable_attributes = %w[id delivery_orders name]


    state_machine :status, initial: :pending do
      event :receive do
        transition to: :received
      end
      after_transition to: :received, do: :after_received

      event :complete do
        transition to: :completed, from: :received
      end
    end

    state_machine :payment_state, initial: :pending do
      event :pay do
        transition to: :paid, from: :pending
      end
    end

    def total_order_qty
      items.sum(:total_items)
    end

    def total_order_received_qty
      items.sum(:qty_received)
    end

    def excess_shipping?
      total_order_qty < total_order_received_qty
    end

    def shortage?
      total_order_received_qty < total_order_qty
    end

    def biaya_per_pcs
      return 0 if biaya_import <= 0 || total_order_received_qty <= 0
      (biaya_import/total_order_received_qty).ceil
    end

    private

    def after_received
      if total_order_qty == total_order_received_qty
        complete!
      end
    end
  end
end

app/controllers/spree/admin/containers_controller.rb
module Spree
  module Admin
    class ContainersController < ResourceController
      def index
        @containers = @containers.filter(params.slice(:sku_contain, :id_is, :name_user)).order(created_at: :desc).page params[:page]  
      end

      def show
        @purchase_order_lines = @container.items.filter(params.slice(:sku_contain))
      end

      def create
        invoke_callbacks(:create, :before)
        @object.attributes = permitted_resource_params
        if @object.save
          invoke_callbacks(:create, :after)
          flash[:success] = flash_message_for(@object, :successfully_created)
          respond_with(@object) do |format|
            format.html { redirect_to new_item_admin_container_path(@object) }
            format.js   { render layout: false }
          end
        else
          invoke_callbacks(:create, :fails)
          respond_with(@object) do |format|
            format.html do
              @suppliers = Spree::Supplier.all
              flash.now[:error] = @object.errors.full_messages.join(", ")
              render_after_create_error
            end
            format.js { render layout: false }
          end
        end
      end

      def new_item
        @search = Spree::PurchaseLineItem.joins(:purchase_order).where("spree_purchase_orders.supplier_id = ? AND 
          spree_purchase_orders.payment_state != ? AND spree_purchase_orders.payment_state != ? AND
          spree_purchase_line_items.shipment_status != ?", @container.supplier_id, "pending", "cart", "completed").ransack(params[:q]) 
        @purchase_order_lines = @search.result.page(params[:page]).per(params[:per_page])
      end

      def update_items
        params[:container_items].each do |x, y|
          next if y["pack"].blank? && y["qty_send"].blank?
          item = Spree::ContainerItem.create!(variant_id: x, qty_send: y[:qty_send], pack: y[:pack], 
            container_id: params[:id], purchase_line_item_id: y[:purchase_line_item_id])
          item.ship!
        end
        flash[:success] = "Berhasil memasukan produk ke kontainer"
        redirect_to request.referrer
      end

      def receive_items
        success = Spree::Container.transaction do 
          params[:container_items].each do |x,y|
            next if y["qty_received"].blank? && y["weight"].blank?
            item = Spree::ContainerItem.shipped.find_by_id x
            next if item.nil?
            item.update_attributes(qty_received: y["qty_received"], weight: y["weight"])
            item.receive!
          end
          @container.receive! if @container.pending?
        end
        if success
          flash[:success] = "Berhasil memperbarui kontainer"
        else
          flash[:alert] = "Gagal memperbarui kontainer"
        end
        redirect_to admin_container_path(@object)
      end

      def selisih_barang
        @search = Spree::ContainerItem.ransack(params[:q]) 
        @items = @search.result.received.where("total_items != qty_received").order(:created_at).page params[:page]
      end

      private

      def whodunnit
        spree_current_user
      end
    end
  end
end

app/views/spree/admin/containers/_form.haml
%legend{:align => "center"} Container
.four.columns.alpha
  = f.field_container :name do
    = f.label :name, "Nama Kontainer", class: 'required'
    %br/
    = f.text_field :name, :class => 'fullwidth title', :required => true
    = f.error_message_on :name
.four.columns.alpha
  = f.field_container :delivery_date do
    = f.label :delivery_date, "Tanggal Berangkat", class: 'required'
    %br/
    = f.text_field :delivery_date, :value => datepicker_field_value(@container.delivery_date), :class => 'datepicker fullwidth'
    = f.error_message_on :delivery_date
.four.columns.alpha
  = f.field_container :eta_date do
    = f.label :eta_date, "Estimasi Sampai", class: 'required'
    %br/
    = f.text_field :eta_date, :value => datepicker_field_value(@container.eta_date), :class => 'datepicker fullwidth'
    = f.error_message_on :eta_date
.four.columns.alpha
  = f.field_container :sack do
    = f.label :sack, "Karung / Koli", class: 'required'
    %br/
    = f.text_field :sack, :class => 'fullwidth title', :required => true
    = f.error_message_on :sack

.clearfix
.five.columns.alpha
  = f.field_container :supplier_id do
    = f.label :supplier_id, "Supplier", class: 'required'
    %br/
    = f.collection_select(:supplier_id, Spree::Supplier.available_to_ship.uniq, :id, :name, { :include_blank => Spree.t('match_choices.none') }, { :class => 'select2 fullwidth' })
    = f.error_message_on :supplier_id
.four.columns.alpha
  = f.field_container :delivery_orders do
    = f.label :delivery_orders, "Surat Jalan", class: 'required'
    %br/
    = f.text_field :delivery_orders, :class => 'fullwidth title', :required => true
    = f.error_message_on :delivery_orders
.three.columns.alpha
  = f.field_container :cbm do
    = f.label :cbm, class: 'required'
    %br/
    = f.text_field :cbm, :class => 'fullwidth title', :required => true
    = f.error_message_on :cbm
- if current_spree_user.admin?
  .four.columns.alpha
    = f.field_container :biaya_import do
      = f.label :biaya_import, "Biaya Import", class: 'required'
      %br/
      = f.text_field :biaya_import, :class => 'fullwidth'
      = f.error_message_on :biaya_import

app/views/spree/admin/containers/index.haml
- admin_breadcrumb(plural_resource_name(Spree::Container))

- content_for :page_actions do
  %li
    = button_link_to "New Container", new_admin_container_url()
= form_for('Filter_container', :as => 'filter_container', method: :get, :url => admin_containers_path) do |f|
  .row 
    .col-sm-4
      .form-group.form-group-default.required
        %label SKU
        = text_field_tag 'sku_contain', nil,class: 'form-control'
    .col-sm-4
      .form-group.form-group-default.required
        %label ID
        = text_field_tag 'id_is', nil,class: 'form-control'
    .col-sm-4
      .form-group.form-group-default.required
        %label Name
        = text_field_tag 'name_user', nil,class: 'form-control'
    .col-sm-6
      = f.submit "Search", class: "btn btn-success"
-if @containers.any? 
  = paginate @containers, theme: "solidus_admin" 
  %table
    %thead
      %tr
        %th.align-left{width: "10%"} Created at
        %th.align-left{width: "5%"} ID
        %th.align-left{width: "17%"} Name
        %th.align-left{width: "10%"} Tanggal Pengiriman
        %th.align-left{width: "10%"} Estimasi Waktu Sampai
        %th.align-left{width: "10%"} Surat Jalan
        %th.align-left{width: "5%"} Karung / Koli
        %th.align-left{width: "3%"} CBM
        %th.align-left{width: "10%"} Total Order Qty (Pcs)
        %th.align-left{width: "10%"} Total Order Received (Pcs)
        %th.align-left{width: "10%"} Shipment State
        - if current_spree_user.admin?
          %th.align-left{width: "10%"} Biaya Import (pcs)
    %tbody
      - @containers.each do |c|
        %tr
          %td= c.created_at.to_date
          %td= link_to c.id, admin_container_path(c.id)
          %td #{c.name}
          %td= c.delivery_date.to_date
          %td= c.eta_date.to_date
          %td= c.delivery_orders
          %td= c.sack
          %td= c.cbm 
          %td= c.total_order_qty 
          %td= c.total_order_received_qty 
          %td= c.status.humanize
          - if current_spree_user.admin?
            %td= number_to_idr c.biaya_per_pcs
          %td.actions
            = link_to_delete c, :no_text => true if can?(:delete, c)
  = paginate @containers, theme: "solidus_admin" 
- else
  .alpha.twelve.columns.no-objects-found
    = render 'spree/admin/shared/no_objects_found', resource: Spree::Container, new_resource_url: new_object_url

app/views/spree/admin/containers/new.haml
= render :partial => 'spree/shared/error_messages', :locals => { :target => @container }
= form_for [:admin, @container], method: :post, url: admin_containers_path, :html => { :multipart => true } do |f|
  %fieldset{"data-hook" => "new_product"}
    = render :partial => "form", locals: {f: f}
    .clearfix
    = render :partial => 'spree/admin/shared/new_resource_links'

app/views/spree/admin/containers/new_item.haml
- admin_breadcrumb("Container: #{@container.supplier.name} / #{@container.name}")
- content_for :page_actions do
  %li
    = button_link_to "Lihat Isi Container", admin_container_path(@container)

- content_for :table_filter do
  %div
    = search_form_for @search, url: new_item_admin_container_path(@container) do |f|
      - locals = {:f => f}
      .row
        .col-xs-4.col-md-offset-4
          .field
            = f.label :variant_sku_cont, Spree::Variant.human_attribute_name(:sku)
            = f.text_field :variant_sku_cont, :size => 15
      .actions.filter-actions
        = button Spree.t(:search)

%fieldset
  %legend{:align => "center"} Product Items
  %table
    %thead
      %tr
        %th Purchase ID
        %th Image
        %th SKU
        %th Pack Qty
        %th Isi per Pack
        %th Total Pieces
        %th Pcs Received
        %th Sisa
        %th Qty Send (pcs)
        %th Pack
    %tbody
      -if @purchase_order_lines.any? 
        = paginate @purchase_order_lines, theme: "solidus_admin" 
        - @purchase_order_lines.each do |line|
          = form_tag update_items_admin_container_path, method: :put do
            %tr
              %td.align-center= link_to line.purchase_order.id, items_admin_purchase_order_path(line.purchase_order.id)
              %td.align-center= image_tag line.variant.display_image.attachment(:mini)
              %td.align-center= line.variant.sku
              %td.align-center= line.quantity
              %td.align-center= line.variant.product.total_items
              %td.align-center= line.items
              %td.align-center= line.total_received
              %td.align-center= line.outstanding_pieces
              %td= text_field_tag "container_items[#{line.variant_id}][qty_send]"
              %td= text_field_tag "container_items[#{line.variant_id}][pack]"
              %td.actions
                = hidden_field_tag "container_items[#{line.variant_id}][purchase_line_item_id]", line.id
                = button_tag "", class: "fa fa-truck icon_link with-tip no-text"
  .align-center

app/views/spree/admin/containers/selisih_barang.haml
- admin_breadcrumb("Selisih Barang")
- content_for :table_filter do
  %div
    = search_form_for @search, url: selisih_barang_admin_containers_path do |f|
      .row
        .col-xs-4
          .field
            = f.label :variant_sku_cont, "Code Item"
            = f.text_field :variant_sku_cont, :size => 15
        .col-xs-4
          .field
            = f.label :container_id_eq, "Container ID"
            = f.text_field :container_id_eq, :size => 15
        .col-xs-4
          .field
            = f.label :container_delivery_orders_cont, "Surat Jalan"
            = f.text_field :container_delivery_orders_cont, :size => 15
      .actions.filter-actions
        = button Spree.t(:search)
-if @items.any? 
  = paginate @items, theme: "solidus_admin" 
  %table
    %thead
      %tr
        %th.align-left Created at
        %th.align-left ID Container
        %th.align-left Image
        %th.align-left Code Item
        %th.align-left Tanggal Pengiriman
        %th.align-left Estimasi Waktu Sampai
        %th.align-left Surat Jalan
        %th.align-left Total Order Qty (Pcs)
        %th.align-left Total Order Received (Pcs)
        %th.align-left Selisih Barang
        %th.align-left Shipment State
    %tbody
      - @items.each do |c|
        %tr
          %td= c.created_at.to_date
          %td= link_to c.container_id, admin_container_path(c.container_id)
          %td= image_tag(c.variant.display_image(fallback: false).attachment(:mini))
          %td= c.variant.sku
          %td= c.container.delivery_date.to_date
          %td= c.container.eta_date.to_date
          %td= c.container.delivery_orders
          %td= c.total_items 
          %td= c.qty_received
          %td= c.qty_received - c.total_items
          %td= c.status.humanize
          - if c.received?
            %td.actions
              - if c.purchase_line_item.paid? && c.shortage?
                = link_to "", refund_admin_container_item_path(c), method: :put, class: 'fa fa-money icon_link with-tip no-text', "data-original-title" => "Refund Deposit", data: {confirm: "Are you sure you want to refund deposit for this item?"}
                = link_to "", treat_as_expense_admin_container_item_path(c), method: :put, class: 'fa fa-cancel icon_link with-tip no-text', "data-original-title" => "Treat as Expense", data: {confirm: "Are you sure you want to treat as expense for this item?"}
              - else
                = link_to "", complete_admin_container_item_path(c), method: :put, class: 'fa fa-capture icon_link with-tip no-text', "data-original-title" => "Mark as Complete", data: {confirm: "Are you sure you want to mark as complete this item?"}
              - if c.excess_shipping?
                = link_to "", generate_po_admin_container_item_path(c), method: :put, class: 'fa fa-book icon_link with-tip no-text', "data-original-title" => "Create Purchase Order", data: {confirm: "Are you sure you want to create purchase order for this item?"}
  = paginate @items, theme: "solidus_admin" 

app/views/spree/admin/containers/show.haml
- content_for :page_actions do
  %li
    = button_link_to "Tambah Barang", new_item_admin_container_url(@container)

= render :partial => 'spree/shared/error_messages', :locals => { :target => @container_items }
= form_for [:admin, @container], method: :put, url: admin_container_path(@container), :html => { :multipart => true } do |f|
  %fieldset{"data-hook" => "new_product"}
    = render :partial => "form", locals: {f: f}
    .clearfix
    = render :partial => 'spree/admin/shared/edit_resource_links'
%fieldset
  %legend{:align => "center"} Product Items
  = form_for('Filter_container', :as => 'filter_container', method: :get, :url => admin_container_path) do |f|
    .row 
      .col-sm-8
        .form-group.form-group-default.required
          %label SKU
          = text_field_tag 'sku_contain', nil, class: 'form-control'
      .col-sm-4
        = f.submit "Search", class: "btn btn-success"
  = form_tag receive_items_admin_container_path, method: :put do
    %table
      %thead
        %tr
          %th.align-left{style: "width: 5%"} Purchase ID
          %th.align-left{style: "width: 10%"} Image
          %th.align-center{style: "width: 20%"} SKU
          %th.align-center{style: "width: 5%"} Qty Send (Pcs)
          %th.align-center{style: "width: 5%"} Isi
          %th.align-center{style: "width: 5%"} Qty
          %th.align-left{style: "width: 5%"} Pack
          %th.align-left{style: "width: 15%"} Qty Received (Pcs)
          %th.align-left{style: "width: 15%"} Weight per Pcs (Kg)
          %th.align-left{style: "width: 15%"} Status
      %tbody
        - @purchase_order_lines.each do |line|
          %tr
            %td= line.purchase_order_id
            %td= image_tag line.variant.display_image.attachment(:mini)
            %td= line.variant.sku
            %td.align-center= line.qty_send
            %td.align-center= line.variant.product.total_items
            %td.align-center= line.quantity
            %td= line.pack
            %td= text_field_tag "container_items[#{line.id}][qty_received]", line.qty_received, disabled: line.received? || line.completed?
            %td= text_field_tag "container_items[#{line.id}][weight]", number_with_precision(line.send(:weight), precision: 2), disabled: line.received? || line.completed?
            %td= line.status.humanize
            %td.actions
              - if line.shipped?
                =link_to "", delete_item_admin_container_item_path(line), class: 'fa fa-trash icon_link with-tip no-text', "data-original-title" => "Delete", data: {confirm: "Are you sure you want to delete this item?"}
              - if spree_current_user.admin?
                -if line.received? || line.completed?
                  =link_to "", reverse_admin_container_item_path(line), class: 'fa fa-undo icon_link with-tip no-text', "data-original-title" => "Reverse", data: {confirm: "Are you sure you want to reverse this item?"}
      %tfooter
        %tr
          %td.align-center{colspan: 3} Total
          %td.align-center #{@purchase_order_lines.sum(:qty_send)}
          %td.align-center
          %td.align-center #{@purchase_order_lines.sum(:quantity)}
          %td.align-center #{@purchase_order_lines.sum(:pack)}
          %td.align-center #{@purchase_order_lines.sum(:qty_received)}

    .align-center
      - if !@container.completed?
        = submit_tag "Submit"